### ISSUE TITLE
Label clickable for parent table in preview mode

### ISSUE THREAD

**Issue by g1n-ru** [moonshine-software/moonshine#1006]
### MoonShine Version

2.14.3

### Laravel Version

11.9.1

### PHP Version

8.2

### Description

https://github.com/moonshine-software/moonshine/assets/147530516/54f8ad8d-0840-4d0c-8312-92893ec51e2e

### Steps To Reproduce

```php
    public function fields(): array
    {
        return [
            Block::make([
                 Switcher::make('Включен', 'is_active')->updateOnPreview()
            ])
        ]);
    }
```

**Comment by lee-to** [comment]
Есть такая проблема в id у элементов формы, мы уже пофиксили в 3 версии но это будет слишком мажорным изменением для второй
можете исправить самостоятельно указав id для индексного поля

Switcher::make('Включен', 'is_active')->updateOnPreview()->setId('index-active')
