### ISSUE TITLE
Проблемы с мобильным меню.

### ISSUE THREAD

**Issue by khlystou** [moonshine-software/moonshine#1023]
### MoonShine Version

2.14

### Laravel Version

10.14

### PHP Version

8.2

### Description

Проблемы при переключении вложенных пунктов меню. Подробности в видео. 

https://github.com/moonshine-software/moonshine/assets/17690542/e4227dcc-3da6-4c71-8de1-f2fbef543ac7

### Steps To Reproduce

Пример записан в реальном времени на текущей версии документации. Файлы кеша очищены.

**Comment by DissNik** [comment]
Уточните мобильный браузер. Смог отловить такое поведение только в браузере от самсунг.

**Comment by khlystou** [comment]
Chrome 125.0.6422.147 (Android 14)

**Comment by DissNik** [comment]
@khlystou обновили доку можно тестить!
У меня проблема ушла

**Comment by khlystou** [comment]
Да. Проблема больше не проявляется. Когда в релиз?)

**Comment by DissNik** [comment]
Это уже в релизе )
