### ISSUE TITLE
URL Field - доработка для title

### ISSUE THREAD

**Issue by origami4love** [moonshine-software/moonshine#1063]
### Description

Если требуется обрезать очень длинную ссылку в колбэке, то она становится битой.
Предлагаю добавить несколько методов, чтоб можно было управлять наименованием ссылки.
https://github.com/moonshine-software/moonshine/blob/0c45cdb2ee6a1937660f7675257cd37fb173b4e4/src/Fields/Url.php#L28 

Не делаю ПР, с мунжайном не так хорошо знаком.

Переопределил класс у себя и сделал так
```php
class Url extends Text
{
    protected string $type = 'url';
    protected int $limit;

    public function limit(int $limit): self
    {
        $this->limit = $limit;

        return $this;
    }

    protected function resolvePreview(): View|string
    {
        $value = parent::resolvePreview();

        if ($this->isRawMode()) {
            return $value;
        }

        if ($value === '0' || $value === '') {
            return '';
        }

        $title = $this->limit ? Str::limit($value, $this->limit) : $value;

        return UrlComponent::make(
            $value,
            $title,
            blank: $this->isLinkBlank()
        )->render();
    }
} 
```
В ресурсе
```php
            Url::make(__('url'), 'url')
                ->limit(30),
```
В админке
![image](https://github.com/moonshine-software/moonshine/assets/173542959/2f2246a2-774d-4e29-a138-c588b9fc4fdc)

**Comment by lee-to** [comment]
сделаем
