### ISSUE TITLE
Маска заменяет значение в поле

### ISSUE THREAD

**Issue by origami4love** [moonshine-software/moonshine#1065]
### Description

Если задать маску
https://moonshine-laravel.com/docs/resource/fields/fields-text?change-moonshine-locale=ru#mask

то при редактировании нельзя изменить значение в поле - оно заменяется на маску

**Comment by DissNik** [comment]
Не смог воспроизвести, у меня все корректно работает. Опишите подробнее и проверьте на наличие ошибок по js

**Comment by lee-to** [comment]
https://alpinejs.dev/plugins/mask убедитесь что используете правильные символы для маски

**Comment by origami4love** [comment]
Пробовал по всякому
результат один и тот же

![image](https://github.com/moonshine-software/moonshine/assets/173542959/cab9faba-91c5-4d2d-b4d1-efd5b72c74e6)

**Comment by origami4love** [comment]
Разобрался. Попутал с плейсхолдером
