### ISSUE TITLE
Validation rules

### ISSUE THREAD

**Issue by VitaliyGromov** [moonshine-software/moonshine#1089]
### MoonShine Version

2.18.1

### Laravel Version

10.48.1

### PHP Version

8.2.17

### Description

![image](https://github.com/moonshine-software/moonshine/assets/101171374/4fdebff8-5c0c-4ba3-81df-edfc497989fe)
Если в методе rules у ресурса определить правило для поля через `Rule:requiredIf(!request()->has('field_name'))`, но при этом добавить, что поле должно быть строкой, то валидация сработает некорректно

`
public function rules(Model $item): array
    {
        return [
            'firstname' => ['nullable', 'string', 'max:255'],
            'lastname' => ['nullable', 'string', 'max:255'],
            'surname' => ['nullable', 'string', 'max:255'],
            'phone' => [Rule::requiredIf(!request()->has('email')), 'string', 'min:11', 'max:11', 'unique:companies'],
            'email' => [Rule::requiredIf(!request()->has('phone')), 'string', 'email','max:255', 'unique:companies'],
        ];
    }
`

В данном примере, действует следующее правило: если не указан телефон, то email обязательно, то же самое и для поля phone. Но если в форме не заполнить phone, срабатывает валидация на то, что поле не является строкой.

Поля в ресурсе определены подобным образом
`public function fields(): array
    {
        return [
            Block::make([
                ID::make()->sortable(),
                Text::make('Имя', 'firstname'),
                Text::make('Фамилия', 'lastname'),
                Text::make('Отчество', 'surname'),
                Text::make('Телефон', 'phone'),
                Text::make('Email', 'email'),
            ]),
        ];
    }
`

### Steps To Reproduce

1) Создать ресурс
2) Создать создать в методе rules массив и определить валидацию подобным образом
3) На странице создания попытаться создать запись

**Comment by lee-to** [comment]
Муншайн не реализует свою валидацию, использует ларавел валидатор
