### ISSUE TITLE
Лишние запросы в metrics при async

### ISSUE THREAD

**Issue by MadZee-M** [moonshine-software/moonshine#1118]
### MoonShine Version

2

### Laravel Version

10

### PHP Version

8.3

### Description

Когда идет запрос на изменения таблицы (async). Также и идут все запросы из метода metrics. Хотя оно не имеет никакого отношения.

Создал костыль.

### Steps To Reproduce

1.  Создал метод в ресурсе

   ```
 public function isCallAsyncTable(): bool {
        return str(request()->route()->action['as'])->endsWith('.async.table');
    }
```

(было бы хорошо, что-то подобное вшить в коробку с нормальной реализацией).

2. 
``` 
public function metrics(): array {
        if ($this->isCallAsyncTable()) {
            return [];
        }
}
```

**Comment by lee-to** [comment]
Ок, глянем что там, пока можете юзать костыль по симпотичнее
if(request()->ajax())
