### ISSUE TITLE
XSS in Markdown and Textarea fields

### ISSUE THREAD

**Issue by andrunio** [moonshine-software/moonshine#1148]
### MoonShine Version

2.19.0

### Laravel Version

10.48.10

### PHP Version

8.2

### Database Driver & Version

MySQL 8.0.34

### Description

If you enter a JS script in the Markdown or Textarea editing form, the script will be executed on the index or detail page of the resource.

![CleanShot 2024-07-31 at 11 55 53@2x](https://github.com/user-attachments/assets/77cd8918-f222-4569-80a8-f8b7c97fed0a)
![CleanShot 2024-07-31 at 11 56 02@2x](https://github.com/user-attachments/assets/c927f6d0-f2bc-4007-92a1-18656d7394b1)

### Steps To Reproduce

1.  Create a field
```php
Markdown::make('Description')
```

2. Fill the value in the edit form and save
```js
<script>alert('ok');</script>
```

**Comment by lee-to** [comment]
Видимо имеется ввиду что на индексной странице выстреливает когда мы выводим значение как оно есть? Так как сам редактор у меня алерт не выводит
