### ISSUE TITLE
Сломанное меню в компоненте TopBar v2.20.0

### ISSUE THREAD

**Issue by Ge1i0N** [moonshine-software/moonshine#1157]
MoonShine Version
2.20.0

Laravel Version
11

PHP Version
8.3

### Description
Сломались стили меню. При разворачивании верхнего меню его подпункты находятся внутри блока и на них нельзя нажать, также появляется внутренняя прокрутка блока.

![image](https://github.com/user-attachments/assets/099084b7-fa79-45e8-bcb6-2846d11dc340)

**Comment by DissNik** [comment]
Проверьте, пожалуйста, что у вас обновились ассеты и не они закэшированы

**Comment by Ge1i0N** [comment]
@DissNik я для проверки развернул с нуля копию из инструкции "Вклад в разработку" - проблема была, в том числе и в чистом новом браузере. При обновлении на живом проекте ассеты новые были сбилжены, кеши все чистились.

**Comment by DissNik** [comment]
Спасибо, буду проверять
