### ISSUE TITLE
Отображение полей с информацией об ошибке валидации

### ISSUE THREAD

**Issue by forest-lynx** [moonshine-software/moonshine#1161]
### Description

Добрый день!
При выводе информации об ошибках валидации во Flex элементе происходит смещение полей ввода относительно общей базовой линии.
![Flex-error](https://github.com/user-attachments/assets/703d2f91-b0b6-4ca4-8247-b3031f1c3e93)

Предложение выводить блок с ошибкой через абсолютное позиционирование.

**Comment by DissNik** [comment]
Используя методы `itemsAlign()` и `justifyAlign()` можно изменить положения элементов во Flex, по умолчанию это center

**Comment by forest-lynx** [comment]
Я в целом про уведомления об ошибках. Было бы хорошо сразу из коробки иметь ровный вид, а не писать для каждого флекса во всех ресурсах одно и тоже.

**Comment by DissNik** [comment]
я пока не вижу решения, как отображать ошибки, если у них абсолютное позиционирование. текст ошибки может быть большим

**Comment by DissNik** [comment]
больше подходит вариант у флексов по умолчанию выравнивание по верхнему краю, но сомневаюсь что такое стоит делать в v2
