### ISSUE TITLE
columnSelection не работает если в базе колонки с большой буквы

### ISSUE THREAD

**Issue by amadeus05** [moonshine-software/moonshine#1164]
### MoonShine Version

2.20

### Laravel Version

11.9

### PHP Version

8.3

### Description

Столкнулся с тем что на проекте таблици в которых все начинается с большой буквы columnSelection отказывается работать с такими колонками

### Steps To Reproduce

Структура таблици в которой у меня появилась данная проблема

--
-- Структура таблиці `Customers`
--

CREATE TABLE `Customers` (
  `ID` bigint(20) NOT NULL,
  `PassionID` int(11) NOT NULL,
  `Email` text COLLATE utf8mb4_bin NOT NULL,
  `Name` text COLLATE utf8mb4_bin NOT NULL,
  `Birthday` date DEFAULT NULL,
  `PreferredName` text COLLATE utf8mb4_bin NOT NULL,
  `Sex` tinyint(1) NOT NULL DEFAULT '1',
  `Phone` text COLLATE utf8mb4_bin NOT NULL,
  `ManychatID` int(11) NOT NULL,
  `Telegram` bigint(20) NOT NULL,
  `TelegramName` text COLLATE utf8mb4_bin NOT NULL,
  `LastActivity` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

**Comment by JeRabix** [comment]
при вставке в localStorage ключи приводяться к нижнему регистру
