### ISSUE TITLE
the field  BelongsTo is reset when reactivy

### ISSUE THREAD

**Issue by ramir1** [moonshine-software/moonshine#1165]
### Description

When changing a BelongsTo, the data is added to currency_multiple, but is reset in the first one. In the server response 
currency_id = null
`                BelongsTo::make('currency')->reactive(),
                Text::make('currency_multiple')->reactive( function (Fields $fields, ?int $value, Text $field, array $values) {
                    $field->setValue(100);
                    return $fields;
                }),`

**Comment by lee-to** [comment]
the BelongsTo doesn't work with integers, it works with models, you need to assign a model

**Comment by ramir1** [comment]
Это поле и работает с моделю. И список для выбора отображается. И все сохраняется нормально. Но, когда добавляю реактивность, то выбранное поле сбрасывается после перезагрузки реактивных полей.

**Comment by lee-to** [comment]
> Это поле и работает с моделю. И список для выбора отображается. И все сохраняется нормально. Но, когда добавляю реактивность, то выбранное поле сбрасывается после перезагрузки реактивных полей.

Понял, на днях попробую воспроизвести у себя и если что сделаю фикс либо открою задачу заного

**Comment by lee-to** [comment]
ну или сделаю рецепт решения

**Comment by lee-to** [comment]
Я нашел проблему и решение, скоро будет фикс релиз но если нет времени ждать то можно применить вот такой хак

```php
BelongsTo::make(
    __('moonshine::ui.resource.role'),
    'moonshineUserRole',
    static fn (MoonshineUserRole $model) => $model->name,
    new MoonShineUserRoleResource(),
)
    ->reactive(),


Email::make(__('moonshine::ui.resource.email'), 'email')
    ->reactive(function(Fields $fields, ?string $value, Email $field, array $values) {
        $fields
            ->findByColumn('moonshine_user_role_id')
            ?->setValue((new MoonshineUserRole())->forceFill($values['moonshine_user_role_id']));

        $field->setValue('test@ya.ru');

        return $fields;
    })
```

**Comment by ramir1** [comment]
спасибо. Подожду.
