### ISSUE TITLE
Is there a way to always show the filter section above the list instead of hiding it?

### ISSUE THREAD

**Issue by anxgstadler** [moonshine-software/moonshine#1168]
### Description

My client wants the filters to always be visible above the list instead of being hidden away.
Is there a way to achive this? So far I've found nothing in the documentation about this.

The current way is quite confusing as people can't see at first glance which filters are available, and if filters are set they don't see which filters are set. Showing the filters (or at least the filters with values) above the list would greatly enhance usability for us.

**Comment by lee-to** [comment]
A page is just a set of components, you can change the set of page components or create your own page, no one prevents you from disabling the button with current filters and making your own on top through the FormBuilder, study the documentation, look at the video guides, we cannot sit and constantly give you ready-made code examples in tasks, most implementations do not depend on Moonshine, knowledge in development and Laravel is needed
