### ISSUE TITLE
Bug in Tabs

### ISSUE THREAD

**Issue by MadZee-M** [moonshine-software/moonshine#1169]
### MoonShine Version

2

### Laravel Version

10

### PHP Version

8.3

### Description

Здравствуйте! Нашел баг с Tabs. Если есть вложенные Tabs с ->vertical(), то дочерние Tabs не отображаются "Вертикально"

### Steps To Reproduce

```
Tabs::make([
  Tab::make('Таб 1')->fields([
      Text::make('Имя')
  ]),
  Tab::make('Таб 2')->fields([
      Tabs::make([
          Tab::make('Sub tаб 1')->fields([
              Text::make('Имя')
          ]),
          Tab::make('Sub tаб 2')->fields([
              Text::make('Имя')
          ]),
      ])->vertical()
  ]),
])->vertical(),
```
Когда переключаю на Tab 2, то получаю горизонтальные Вкладки (вместо вертикальных)

![image](https://github.com/user-attachments/assets/cb0dd87f-efd7-4af4-b767-9199ab24974f)

А если изменить размер окна браузера, то получаю ожидаемый результат.

![image](https://github.com/user-attachments/assets/e5112149-0788-4c66-82fe-ab0c09ea9d2e)

**Comment by DissNik** [comment]
может быть просто не умещаются, по умолчанию ширина блока 480px, если меньше то вертикальные вкладки отображаться не будут, можно попробовать задать ширину

```php
Tabs::make([
    //...
])
    ->customAttributes([ 'data-tabs-vertical-min-width' => 300]) 
```

**Comment by MadZee-M** [comment]
> может быть просто не умещаются, по умолчанию ширина блока 480px, если меньше то вертикальные вкладки отображаться не будут, можно попробовать задать ширину
> 
> ```
> Tabs::make([
>     //...
> ])
>     ->customAttributes([ 'data-tabs-vertical-min-width' => 300]) 
> ```

А почему, если я дочерние "Вкладки", перенесу наверх (сделаю родителями), то срабатывает как положено?

Даже на скриншотах видно, что родительские Вкладки имеют меньше ширины, чем дочерние. 

Даже если так, то почему срабатывают при изменения размера окна браузера (как я понял .trigger('resize'))

**Comment by DissNik** [comment]
дочерние вкладки не могут быть больше чем родительский блок

**Comment by DissNik** [comment]
я понял, что вы имели в виду, при загрузке срабатывает только первый уровень вкладок

**Comment by MadZee-M** [comment]
> я понял, что вы имели в виду, при загрузке срабатывает только первый уровень вкладок

Верно
