### ISSUE TITLE
Проблема с BelongsToMany

### ISSUE THREAD

**Issue by Sckatik** [moonshine-software/moonshine#1204]
### MoonShine Version

2.20.9

### Laravel Version

10.48.20

### PHP Version

8.2.4

### Database Driver & Version

MYSQL

### Description

Некорректная работа  BelongsToMany - на предыдущих версиях moonshine данное поле работало корректно. После обновление на версию 2.20.9 появились ошибки при сохранении.
В Resource:
```
BelongsToMany::make('Режиссеры', 'directors', resource: new DirectorResource())
                         ->withImage('image', 'public', 'directors')
                            ->asyncSearch()->creatable()
```

По коду ничего не менял. Как то по другому нужно теперь данное поле вызывать? Или это баг?

При сохранении ошибка - SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '${index0}' for column 'director_id' at row 1

Весь js обновил в папке pulbic/vendor/moonshine

Скрин html из админки

![image](https://github.com/user-attachments/assets/f1ece1d2-90d8-4c1d-8997-d9dcbe84ec0f)

### Steps To Reproduce

Выбираю в чекбоксе запись:
![image](https://github.com/user-attachments/assets/7346c7f1-ed97-4a02-8bfc-d01ae949db92)

Нажимаю сохранить:
![image](https://github.com/user-attachments/assets/09e5c264-0130-4a7f-9d2d-fadbdec55a51)

**Comment by lee-to** [comment]
Привет! Вот пр с фиксом - https://github.com/moonshine-software/moonshine/pull/1195
Релиз будет в пн, если сможешь прогнать этот пр на своем кейсе и проверить то буду признателен

**Comment by Sckatik** [comment]
Привет, протестил, проблема решилась. Спасибо! Наткнулся тут еще на 1 баг. Когда создаешь новую запись через creatable() перестал работать режим reactive для slug. Пока отключил. Создам тогда отдельный issue?

**Comment by lee-to** [comment]
> Привет, протестил, проблема решилась. Спасибо! Наткнулся тут еще на 1 баг. Когда создаешь новую запись через creatable() перестал работать режим reactive для slug. Пока отключил. Создам тогда отдельный issue?

Да
