### ISSUE TITLE
Fix footer sidebar (v1.5)

### ISSUE THREAD

**Issue by DissNik** [moonshine-software/moonshine#121]
![image](https://user-images.githubusercontent.com/12373059/227152837-afb855e8-a0a0-408e-bda2-853cdad1c020.png)

**Comment by lee-to** [comment]
До сих пор актуально?

**Comment by DissNik** [comment]
немного по другому я себе представлял как зафиксировать футер :)
![image](https://user-images.githubusercontent.com/12373059/229340010-daf99615-05e2-4e33-bec9-c7a04ad63018.png)
вот эту часть я думал оставить, а скролить только меню

**Comment by DissNik** [comment]
так то все нормально, это мои личные придирки, можно закрыть

**Comment by lee-to** [comment]
Ну если что после релиза сделаешь pr и изменим
