### ISSUE TITLE
[3.x] Add sticky columns feature to resource tables

### ISSUE THREAD

**Issue by lee-to** [moonshine-software/moonshine#1212]
### Discussed in https://github.com/orgs/moonshine-software/discussions/1211

<div type='discussions-op-text'>

<sup>Originally posted by **savosik** August 28, 2024</sup>
- Allow resource classes to define which columns should be fixed when the table exceeds the viewport width.
- (Optionally) Provide a way for users to pin/unpin columns so they remain visible when scrolling large tables horizontally.
- 
![fixed_columns](https://github.com/user-attachments/assets/e1a7a083-7e17-47c7-a3c6-d8b9b975b93a)

</div>

**Comment by savosik** [comment]
![chrome-capture-2024-8-29](https://github.com/user-attachments/assets/0dda5bd9-a370-4272-8aa6-f4406c7ba03c)
