### ISSUE TITLE
Multiple authentication using moonshine for both cabinets

### ISSUE THREAD

**Issue by uzb-sensei** [moonshine-software/moonshine#1228]
### Description

I thought Multiple authentication using moonshine for both cabinets was possible, but when I started I ran into a problem with Profile in Layout:
Profile Component in vendor:
![Снимок](https://github.com/user-attachments/assets/c1006536-3a41-4345-a85e-85338643bf08)
MoonShineAuth:
![Снимок2](https://github.com/user-attachments/assets/f7105a2f-762d-4e90-9511-d8ed7ee4068c)
But this can be solved by creating your own Profile component for Layout.
For multiple authentication I use 'moonshine' guard and 'staff' guard. Two login forms in different route prefix (/staff and / for original users). That's why I need to change prefix in config of moonshine.
Also if you look at the routes of moonshine, you will see that middleware for routes are from config, but I need changeable guard based on url.
![Снимок3](https://github.com/user-attachments/assets/db5562aa-8c2f-4b17-81e9-91fb90a6f562)
That's why in current versions of MoonShine it's impossible to make multipple authentication!

**Comment by lee-to** [comment]
no one forces you to use the configureRoutes method

```php
Route::group([
            'prefix' => 'admin',
            'middleware' => 'moonshine',
            'as' => 'moonshine.',
        ], function() {
// Routes
});

Route::group([
            'middleware' => 'moonshine',
        ], function() {
// Other routes
});
```
