### ISSUE TITLE
Field - $formatted - Не обрабатываются relations в $item в фукнции

### ISSUE THREAD

**Issue by ArtemYurov** [moonshine-software/moonshine#1235]
### MoonShine Version

2.21.2

### Laravel Version

10.48.20

### PHP Version

8.3.6

### Description

Код
`Number::make('Сумма', 'currency_balance_invoice.sum_currency', fn($item) => $item->currency_balance_invoice->sum_currency),`

Ошибка
`Attempt to read property "sum_currency" on null `

Но дамп при этом отрабатывает нормально, показывает значение
`fn($item) => dd($item->currency_balance_invoice->sum_currency)`

Без указания $formatted отображает нормально

### Steps To Reproduce

`Number::make('Сумма', 'currency_balance_invoice.sum_currency', fn($item) => $item->currency_balance_invoice->sum_currency),`

**Comment by lee-to** [comment]
Проверил у себя все норм! Видимо просто не правильно дампите и там есть роу где реально null! В целом чтобы вы понимали дот нотация это просто вызов хелпера data_get и важно чтобы все элементы сразу были в объекте а второй вызов от объекта $item это уже за счет магии Eloquent
В целом я бы мог еще уточнять кучу вопросов чтобы определить именно ваш кейс но поле Number не имеет отношения к отношениям поэтому стройте логику не через дот нотация а через formatted или changeFill/changePreview

p.s и в целом такие построение примитивных полей с отношениями как правило ошибка архитектуры вашего подхода

**Comment by ArtemYurov** [comment]
дамп делаю прямо в closure
`Text::make('Кол-во', 'currency_balance_invoice.total_quantity', fn($item) => dd($item->currency_balance_invoice->total_quantity))`

Результат:
`120 // app/MoonShine/Resources/CurrencyBalanceDocumentResource.php:79`

я правильно понимаю в момент вызова dd($item->currency_balance_invoice ...тут уже происходит магия Eloquent?
но мне тогда непонятно почему она не происходит в моменте fn($item) => $item->currency_balance_invoice->total_quantity

а вот так
`Text::make('Кол-во', 'currency_balance_invoice.total_quantity', fn($item) => $item->currency_balance_invoice)` 
в значение выводится объект в  json 
`{"id":11,"currency_balance_counterparty_id":2,`


я пока не могу понять какие могут быть ошибки, если я просто использую BelongTo

```
class CurrencyBalanceDocument extends MyModel
{
    public function currency_balance_counterparty(): BelongsTo
    {
        return $this->belongsTo(CurrencyBalanceCounterparty::class);
    }

    public function currency_balance_invoice(): BelongsTo
    {
        return $this->belongsTo(CurrencyBalanceInvoice::class);
    }
}
```

**Comment by ArtemYurov** [comment]
ну да, тут вопрос не к дот нотации, а к formatted, не понимаю почему не отрабатывает
