### ISSUE TITLE
Класс MoonShine\Resources\ModelResource имеет приватный метод afterSave()

### ISSUE THREAD

**Issue by abduraim** [moonshine-software/moonshine#1241]
### Description

Добрый день. При кастомизации функционала появилась необходимость переопределения функционала MoonShine-ресурса. Мы переопределили методы save, delete, massDelete оставив всю вашу логику, за исключением превентивной обработки eloquent-моделей. Пришлось дополнительно переопределять метод afterSave()? т.к. он единственный имеет область видимости private. 

**Версия MoonShine**: 2.21.1
**Источник**: MoonShine\Resources\ModelResource.php

![2024-09-04_10-54](https://github.com/user-attachments/assets/acb50ce9-cfc5-4313-9cb5-8317011f8861)

Спасибо вам, за ваш продукт.

**Comment by lee-to** [comment]
Это просьба сделать его protected?

**Comment by lee-to** [comment]
Сделал протектед

**Comment by abduraim** [comment]
> Сделал протектед

Да, супер, спасибо!
