### ISSUE TITLE
Ошибочный phpdoc в шаблоне

### ISSUE THREAD

**Issue by abduraim** [moonshine-software/moonshine#1242]
### Description

Добрый день. При генерации MoonShineResource через консольную команду у метода formFields() указан неправильный phpdoc.

Пример:
```
/**  
 * @return Field  
 */
public function formFields(): array
```

Версия MoonShine: 2.21.1

Спасибо вам за ваш продукт.

**Comment by lee-to** [comment]
https://github.com/moonshine-software/moonshine/blob/2.x/src/Traits/Resource/ResourceWithFields.php вижу что сейчас все гуд

**Comment by abduraim** [comment]
> https://github.com/moonshine-software/moonshine/blob/2.x/src/Traits/Resource/ResourceWithFields.php вижу что сейчас все гуд

Да, супер, спасибо!
