### ISSUE TITLE
TinyMCE relative/absolute path to images (remove_script_host)

### ISSUE THREAD

**Issue by JeRabix** [moonshine-software/moonshine#1250]
### Description

When use TinyMCE field with laravel-filemanager integration, after save, all links to images changes to relative path

example: /path/to/image.png

we have cases when moonshine admin panel - it's only admin panel + API project, so frontend has another host

for fix this - need provide `remove_script_host: false` with initialize TinyMCE editor in JS

**Comment by JeRabix** [comment]
```php
TinyMce::make('Контент', 'content
                    ->addConfig('remove_script_host', false),
```

this work fine, but maybe we can add global project setting for this or set false by default)

**Comment by DissNik** [comment]
Try using the `addConfig()` method
 
```php
TinyMce::make()->addConfig('remove_script_host', false);
```

**Comment by DissNik** [comment]
> ```
> TinyMce::make('Контент', 'content
>                     ->addConfig('remove_script_host', false),
> ```
> 
> this work fine, but maybe we can add global project setting for this or set false by default)

only in MoonShine 3

**Comment by JeRabix** [comment]
In 2 version can create own field:

```php
<?php

namespace App\MoonShine\Fields;

use MoonShine\Fields\TinyMce;

class TinyMceWithAbsolutePathImages extends TinyMce
{
    public array $config = [
        'remove_script_host' => false,
    ];
}

```
