### ISSUE TITLE
"Not Choose all" not working on IndexPage of Resource

### ISSUE THREAD

**Issue by uzb-sensei** [moonshine-software/moonshine#1256]
### MoonShine Version

2.21

### Laravel Version

11.9

### PHP Version

8.3

### Database Driver & Version

MySQL

### Description

https://github.com/user-attachments/assets/b1bd98c3-3ba1-496e-b24a-fbd5697a4f97
I am using resource with pages (index, detail, form)
IndexPage looks like this:
![Снимок](https://github.com/user-attachments/assets/e4dc14d9-0c89-434a-a82b-86661c62ba56)
But on default resource it works good (as I showed in video)

### Steps To Reproduce

Just create resource with pages, add some fields, add minimalistic style and try to choose all lines

**Comment by uzb-sensei** [comment]
Doesn't work with HasMany field either
![Снимок](https://github.com/user-attachments/assets/905a533c-547c-4aec-ba61-9a2c0cfd5ba4)

**Comment by uzb-sensei** [comment]
**It works only if ID field was initialized.** If it's not there, it won't work. **And no matter which resource has been created (In all types of resources it doesn't work)**

**Comment by lee-to** [comment]
ID is required
