### ISSUE TITLE
Allowed memory size exhausted при вызове Position::make()

### ISSUE THREAD

**Issue by ArtemYurov** [moonshine-software/moonshine#1257]
### MoonShine Version

3.x-dev

### Laravel Version

10.48.2

### PHP Version

8.3.1

### Description

- Вызов Position::make() выдает:
`PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in vendor/laravel/framework/src/Illuminate/Collections/Arr.php on line 911`

### Steps To Reproduce

Добавить  Position::make() в indexFields()

**Comment by lee-to** [comment]
Спасибо пофиксил! Но по 3 лучше пока без issue и все писать в дискуссиях альфа релиза
