### ISSUE TITLE
Custom attributes not applied for URL field

### ISSUE THREAD

**Issue by iPabro** [moonshine-software/moonshine#1266]
### MoonShine Version

2.22.1

### Laravel Version

v10.48.20

### PHP Version

8.2.10

### Description

The customAttributes method is not applying custom styles to the Url field at all.

### Steps To Reproduce

Here is the code I'm using:

```
Url::make('Ссылка из', 'from_url_original')
    ->blank()
    ->customAttributes(['style' => 'width:10px']);
```

**Comment by lee-to** [comment]
Проверил, работает! Речь про отображение в форме или в превью? если превью то там не вешаются атрибуты на значение, их регулировать нужно через  TableBuilder или tr/tdAttributes в ресурсе или через компонент Td
