### ISSUE TITLE
Issues with simultaneous use of reactive() and asyncSearch() in BelongsTo field

### ISSUE THREAD

**Issue by savosik** [moonshine-software/moonshine#1268]
### Description

When using both `reactive()` and `asyncSearch()` methods on a `BelongsTo` field, the following problems are observed:

1. After initiating a search in the field, the reactive callback is triggered, which resets the field and clears the selection options.

2. After selecting a specific option, the reactive callback is triggered, which sets the desired value to the target field, but clears the value of the BelongsTo field itself.

Example code:

```php
BelongsTo::make('Product', 'product', resource: new ProductResource())
    ->required()
    ->asyncSearch()
    ->reactive(function (Fields $fields, ?string $value, Field $field, array $values) {
        $product = Product::find($value);
        return tap($fields, function ($fields) use ($product, $value) {
            $fields->findByColumn('product_price')
                ?->setValue($product?->sell_price ?? 0);
        });
    }),
Text::make('Product Price', 'product_price')->reactive(),

**Comment by lee-to** [comment]
При использовании belongsto в такой связке нужно самостоятельно в колбеке сетить модель в belongsto, это связано с тем что в запросе идут примитивные данные где значение поя будет int, поэтому нужно самостоятельно сеттить
