### ISSUE TITLE
->showWhen after loading the page it doesn't work

### ISSUE THREAD

**Issue by MadZee-M** [moonshine-software/moonshine#1271]
### MoonShine Version

2

### Laravel Version

10

### PHP Version

8.3

### Description

`->showWhen()` не работает, после загрузки страницы. Нужно выполнить действие с полем.

### Steps To Reproduce

Добавляем

```php
Switcher::make('Enable', 'enable');

Text::make('Title', 'title')
  ->showWhen('enable', '=', 1);
```

Поле остаются открытым, хотя он должен быть закрытым, когда enable = 0.
Работает корректно, если нажать на ползунок.

**Comment by lee-to** [comment]
Проверил именно этот кейс в ArticleResource только там был свитчер acitve и все работает

**Comment by MadZee-M** [comment]
> Проверил именно этот кейс в ArticleResource только там был свитчер acitve и все работает

Проверил в других ресурсах и страницах, все четко работает.

Оказывается, проблема было в изменении id формы. Я поменял id у формы на кастомную.

**Comment by lee-to** [comment]
> > Проверил именно этот кейс в ArticleResource только там был свитчер acitve и все работает
> 
> Проверил в других ресурсах и страницах, все четко работает.
> 
> Оказывается, проблема было в изменении id формы. Я поменял id у формы на кастомную.

лучше всегда при создании issue давать всю информацию
