### ISSUE TITLE
Mixed Light and dark theme UI elements

### ISSUE THREAD

**Issue by ciacob** [moonshine-software/moonshine#1279]
### MoonShine Version

3.3.4

### Laravel Version

N/A

### PHP Version

N/A

### Database Driver & Version

N/A

### Description

The Moonshine IDE mixes very bright and dark UI elements, thus making futile any attempts to use it for long periods of time. You should stick to a consistent dark theme (preferably) or a light theme (which I can reverse with a global screen inverter). But the way it is, Moonshine is really not an option for my light sensitive
![Screenshot 2024-09-25 113024](https://github.com/user-attachments/assets/79dedd3f-f8db-4a8a-af8f-2a592fc4547e)
 eyes.

### Steps To Reproduce

**Steps to Reproduce:**

1. Download and install Moonshine.
2. Upon launch, the "Getting Started" tab opens automatically.

**Observed Behavior:**

- The "Getting Started" tab displays a bright/light UI, in contrast to the dark UI theme used by the rest of the interface.

**Expected Behavior:**

- The "Getting Started" tab should align with the dark theme to maintain consistency across the UI.

**Impact:**

- The inconsistency between light and dark elements negatively impacts the overall usability and user experience.

**Comment by lee-to** [comment]
you mixed up the repository, we have laravel admin panel
