### ISSUE TITLE
Minimalistic theme switcher package

### ISSUE THREAD

**Issue by awe-ux** [moonshine-software/moonshine#1293]
### Description

Этот пакет предоставляет возможность изменения стандартной темы на минималистичную. Пакет реализован на основе cookie. В пакете представлен config.php, в котором можно изменить:
- Название, значение и время жизни cookie; 
- Подключение файла со стилями minimalistic.css
- Цвета, которые применяются в минималистичной теме

Ссылка на [репозиторий](https://github.com/awe-ux/moonshine-theme-switcher)

**Comment by lee-to** [comment]
Поддержка 3 версии есть/будет?

**Comment by awe-ux** [comment]
> Поддержка 3 версии есть/будет?

Да, в планах есть такое

**Comment by lee-to** [comment]
и в чат к нам вступайте

**Comment by awe-ux** [comment]
> и в чат к нам вступайте

Этот чат или есть какой-то другой?)
t.me/moonshine_ru

**Comment by lee-to** [comment]
> > и в чат к нам вступайте
> 
> Этот чат или есть какой-то другой?) t.me/moonshine_ru

да этот

**Comment by lee-to** [comment]
Только сейчас заметил что это issue) такие вещи нужно писать в дискуссиях - https://github.com/moonshine-software/moonshine/discussions
