### ISSUE TITLE
проблема с полем HasMany в трейте ResourceModelQuery.

### ISSUE THREAD

**Issue by Galinka999** [moonshine-software/moonshine#1294]
### Description

Создала 2 таблицы со связью hasMany и ресурсы к ним. Родительский ресурс ProductsResource и дочерний TasksResource.
При добавлении в поле HasMany в родительском ресурсе метода creatable() или добавлении в дочернем ресурсе 'massDelete', в родительском ресурсе при переходе на детальную страницу выходит ошибка.

![Снимок экрана от 2024-10-09 16-42-12](https://github.com/user-attachments/assets/6c6f441c-9850-42c1-b9e8-5f71fdf1cad1)

ProductsResource с первичным ключом uuid. TasksResource с первичным ключом id.
Немного поковырялась и нашла кое-что, возможно пригодится для решения проблемы.
Когда  идет проверка прав на кнопку create например, мы попадаем в трейт ResourceModelPolicy метод can().
Там мы ищем getItem(). На нем и происходит ошибка.
![Снимок экрана от 2024-10-09 16-51-01](https://github.com/user-attachments/assets/577d656f-5818-45d5-9146-323fde3013be)
Для поиска getItem() используется трейт ResourceModelQuery.
![Снимок экрана от 2024-10-09 16-52-38](https://github.com/user-attachments/assets/6d1e9b48-c26a-4286-a2aa-4892e017e1f8)
И при hasMany в этот трейт видимо приходит $this - это дочерний ресурc TasksResource, а найти мы пытаемся в бд по $this->getItemID() - а это id продукта. 

Ошибка воспроизводится, если moonshine()->authorizationRules() не пустой. У меня установлен тут установлен пакет moonshine/permissions.

**Comment by lee-to** [comment]
Я сделал все как вы пишите и ошибку пока поймать не могу, нужны еще подробности, попробуйте сами воспроизвести тоже самое в новом проекте

**Comment by Galinka999** [comment]
а moonshine/permissions вы установили?

**Comment by Galinka999** [comment]
Дело даже не только в моей проблеме. В общем, даже если ошибки у вас нет, задампите что приходит в этот трейт из HasMany. Туда приходит дочерний ресурс. а ищем по родительскoму id.

**Comment by lee-to** [comment]
> а moonshine/permissions вы установили?

да, я еще и собственные authorizationRules на всякий добавил
