### ISSUE TITLE
Отсутствует название графика (v1.5)

### ISSUE THREAD

**Issue by DissNik** [moonshine-software/moonshine#131]
![image](https://user-images.githubusercontent.com/12373059/229152451-42755fb1-cbfa-4076-9559-5a83d9a0a591.png)

**Comment by alexvenga** [comment]
Это не название)
Это "Легенда")))

Но, видимо, поникшего - в демократий проекте у меня уже есть

**Comment by DissNik** [comment]
В последний раз проценты пропали :)

**Comment by DissNik** [comment]
Легенда как раз отображается, а вот заголовка нет, график чего изображен? apple и cutcode,  а что? хотя в коде указано
DonutChartMetric::make('Подписчики')->values(['CutCode' => 10000, 'Apple' => 9999])
     
Если править то наверное надо предусмотреть возможность что заголовка может не быть, иногда это надо

**Comment by DissNik** [comment]
что если сделать вот так?
![image](https://user-images.githubusercontent.com/12373059/229293038-28061442-fd14-4fca-8533-916ae456ba0c.png)
![image](https://user-images.githubusercontent.com/12373059/229293232-ebd23bb3-66b5-4fb2-ab09-66bc9f12d5a1.png)

**Comment by lee-to** [comment]
> что если сделать вот так?
> ![image](https://user-images.githubusercontent.com/12373059/229293038-28061442-fd14-4fca-8533-916ae456ba0c.png)
> ![image](https://user-images.githubusercontent.com/12373059/229293232-ebd23bb3-66b5-4fb2-ab09-66bc9f12d5a1.png)

Ну лучше сверху слева а то по центру как то выбивается из общего дизайна

**Comment by DissNik** [comment]
это так реализовано у donut-chart, я просто включил в опциях

**Comment by lee-to** [comment]
> это так реализовано у donut-chart, я просто включил в опциях

Тогда давай)

**Comment by DissNik** [comment]
> Тогда давай)

так уже :) я включил по глупости в pr #149 
уже хотел делать pr чтоб откатиться
