### ISSUE TITLE
Cannot get element in element buttons() method of resource.

### ISSUE THREAD

**Issue by uzb-sensei** [moonshine-software/moonshine#1310]
### Description

I am doing copy button on every (default) resource page:
![Снимок](https://github.com/user-attachments/assets/fae0cab5-5c83-4f24-9a23-e914eecffd9f)
But i cannot get element for ActionButton->onClick method. If I do ActionButton->onClick(function ($item) { .. }) $item is null.
Please make element available to get in element buttons (https://moonshine-laravel.com/docs/resource/models-resources/resources-buttons#buttons)

**Comment by lee-to** [comment]
Сделал в 3 версии а в 2 можно через компонент Td или через метод onAfterSet
