### ISSUE TITLE
 protected bool $errorsAbove = false does not working

### ISSUE THREAD

**Issue by Luisby47** [moonshine-software/moonshine#1311]
### Php: 8.2
I maked a custom model user and setted this resource parameter however it still does not working!!

![image](https://github.com/user-attachments/assets/f5d645b7-f207-40fb-8df4-34544f7d6ee8)

The next one image is about page of profile. 
![image](https://github.com/user-attachments/assets/38b3c654-9c10-4b54-9b62-8601134fc69f)

**Comment by lee-to** [comment]
the feature appeared in update 2.20.4
