### ISSUE TITLE
Call to undefined method MoonShine\\Laravel\\Http\\Responses\\MoonShineJsonResponse::status()

### ISSUE THREAD

**Issue by MadZee-M** [moonshine-software/moonshine#1315]
### MoonShine Version

3

### Laravel Version

11

### PHP Version

8.3

### Description

В middleware вызываю метод `status` у `response`, получаю ошибку.

### Steps To Reproduce

Создаем middleware.

```php
$response = $next($request);
dump($response->status());
return $response;
```

**Comment by lee-to** [comment]
Спасибо! Исправлено
