### ISSUE TITLE
DirectoryNotFoundException

### ISSUE THREAD

**Issue by Ard2p** [moonshine-software/moonshine#1323]
### MoonShine Version

3.0.0-beta.1

### Laravel Version

11

### PHP Version

8.3

### Description

![image](https://github.com/user-attachments/assets/31d9f56e-919f-4b14-9b25-50f6bacd3a09)

проблема в MoonShineServiceProvider 262 строчка

$this->loadViewsFrom(__DIR__ . '/../../resources/views', 'moonshine');

Ведет на несуществующий каталог, что приводит к ошибкам

Symfony\Component\Finder\Exception\DirectoryNotFoundException 

### Steps To Reproduce

Установить муншайн, запустить оптимайз

**Comment by Ard2p** [comment]
Увидел что в деве поправили.

**Comment by lee-to** [comment]
Ишью по 3 версии будем принимать после rc1
