### ISSUE TITLE
Weird searchable select behavior

### ISSUE THREAD

**Issue by Katel1ne** [moonshine-software/moonshine#1334]
### MoonShine Version

2.23.0

### Laravel Version

11.30.0

### PHP Version

8.3.12

### Database Driver & Version

PostgreSQL 16.3

### Description

![image](https://github.com/user-attachments/assets/a29913bf-8599-4b86-a5ac-5a21f999497f)
Searching in select files with numbers gives strange results

### Steps To Reproduce

Use select input with options containing numbers, then try to filter it
Example is shown above, Test 1234 was input, while Test 10.37 still not filtered out

**Comment by lee-to** [comment]
asyncSearch or just searchable? if the second then there is a default search from the library choices.js

**Comment by Katel1ne** [comment]
Yeah, just searchable, without async. Tested choices.js in playground - can confirm, same issue.
But from searching it there I've found next comment - https://github.com/Choices-js/Choices/issues/135#issuecomment-1492853062
I think we should have ability to pass choices.js options and docs should cover this topic, as I think this problem can be pretty common when user wants to get exact match.

**Comment by lee-to** [comment]
```json
fuseOptions: {
    threshold: 0,
    ignoreLocation: true
}
```

It seemed to me that the behavior of the options from the issue is more obvious by default, for now we will leave it by default and then add the ability to configure it for yourself
