### ISSUE TITLE
Таблицы не адаптивны к ширине экрана

### ISSUE THREAD

**Issue by kkit** [moonshine-software/moonshine#1338]
### MoonShine Version

2.22

### Laravel Version

11.9

### PHP Version

8.2

### Description

Длинный текст в таблицах не адаптируется к ширине экрана. (не переносится на новую строку внутри ячейки, а наезжает на соседнюю ячейку)

### Steps To Reproduce

Открыть демо на мобильном телефоне

**Comment by lee-to** [comment]
Универсального решения нет, вам нужно добавить стили на ячейку самостоятельно через tdAttributes или компонент Td
