### ISSUE TITLE
app.js

### ISSUE THREAD

**Issue by abdullajon8111** [moonshine-software/moonshine#1341]
### MoonShine Version

2.23.1

### Laravel Version

11.31

### PHP Version

8.3

### Description

![image](https://github.com/user-attachments/assets/554b23be-5dfc-4d00-afa7-48452cb998c8)

### Steps To Reproduce

![image](https://github.com/user-attachments/assets/becf42ef-18ae-45fa-b90f-ecd635c14074)

**Comment by lee-to** [comment]
and how do we reproduce this?

**Comment by lee-to** [comment]
I think you are using a language that is not supported in moonshine, make sure that the language that is included in the config is present in the lang files

**Comment by abdullajon8111** [comment]
Thank you)
