### ISSUE TITLE
[3.x] HasMany::modifyBuilder

### ISSUE THREAD

**Issue by ArtemYurov** [moonshine-software/moonshine#1344]
### MoonShine Version

 3.x-dev 856a134

### Laravel Version

 11.34.2 

### PHP Version

 8.3.12

### Description

У HasMany должен работать modifyBuilder?
Если да, то он не срабатывает 

### Steps To Reproduce

```
protected function indexFields(): iterable
{
    return [
…
        HasMany::make('Сущности', 'moysklad_load_statuses', resource: MoyskladLoadStatusResource::class)
            ->modifyBuilder(fn(Relation $relation) => $relation->orderBy('entity_at', 'desc')),

    ];
}
```

**Comment by lee-to** [comment]
Ну он и в 2 не работал в режиме превью - индексная страница но в 3 сделаем (уже почти сделали)
