### ISSUE TITLE
[3.x] ModelResource - не показывается таблица после асинхронной загрузки, если до этого не были найдены записи

### ISSUE THREAD

**Issue by ArtemYurov** [moonshine-software/moonshine#1345]
### MoonShine Version

3.x-dev 856a134

### Laravel Version

11.34.2

### PHP Version

8.3.12

### Description

Если в таблице (в modelResource) изначально не было записей и показывалось сообщение
![telegram-cloud-photo-size-2-5348312256343043406-x](https://github.com/user-attachments/assets/65cba462-099c-4480-98a6-c275cda069fc)
то после выполения event на обновление и асинхронной загрузке новых записей, таблица не показывается

### Steps To Reproduce

```
    public function modifyListComponent(ComponentContract $component): ComponentContract
    {
        return $component
            ->simple()
            ->whenAsync(
                function(TableBuilder $table) {
                    // тут загружаем записи в таблицу
                    return $table;
                }
            );
    }
```
и кнопка обновить
```
                    ActionButton::make('Обновить')
                        ->async(events: [AlpineJs::event(JsEvent::TABLE_UPDATED, $this->getListComponentName())]),

```

**Comment by dev-lnk** [comment]
Таблица полностью пустая, делаю так:

```
public function modifyListComponent(ComponentContract $component): ComponentContract
{
    return $component
        ->simple()
        ->whenAsync(
            function(TableBuilder $table) {
                $new = News::create([
                    'name' => 'test_' . time(),
                    'content' => 'content_' . time(),
                ]);
                $table->items([$new]);
                return $table;
            }
        );
}
```
Все работает, необходимо больше инфы, либо проблема вот тут `// тут загружаем записи в таблицу`

**Comment by ArtemYurov** [comment]
Извиняюсь, просмотрел, по факту нужно было ещё перезагрузить значения ресурса:

return $table->items($this->getItems());

У меня же написано просто return $table;

Но тут возникает другая ситуация с этим кейсом.
В ресурсе асинхронное обновление ещё вызывают фильтрация, queryTag и сортировка. И в итоге в эти разы мы будем вызывать обновление данных, что не очень удобно. То есть использование whenAsync в ресурсе становится более ограничено в возможностях, чем на странице. По идее видится так: что есть системные события - фильтрация, сортировка, а есть обновление, вызываемое пользователем.

Но это видимо уже не баг а фича)
