### ISSUE TITLE
[3.x] modelResource $assets 

### ISSUE THREAD

**Issue by ArtemYurov** [moonshine-software/moonshine#1346]
### MoonShine Version

3.x-dev 856a134

### Laravel Version

11.34.2

### PHP Version

8.3.12

### Description

Так как так теперь сделать нельзя:
```
protected array $assets = [Css::make('test.css'), InlineCss::make(".table-sticky {max-height: 83dvh;}")];
```

А можно так:
```
public function getAssets(): array
{
    return [Css::make("test.css"), InlineCss::make(".table-sticky {max-height: 83dvh;}")];
}

```

То нужен метод с каким то более осмысленным называнием, который можно будет добавить в документацию.

Также проблема, что добавленные $assets как через getAssets, так и для компонента через addAssets 
добавляются перед основными css файлами, а должны после:
```
    <style>
                .box-shadow:before {
                    display: none
                }
            </style>
    <style>.table-sticky {max-height: 83dvh;}</style>
    <script src="http://test.test/vendor/moonshine/assets/app.js?v=3.9999999.9999999.9999999-dev" defer=""></script>
    <link href="http://test.test/vendor/moonshine/assets/main.css?v=3.9999999.9999999.9999999-dev" rel="stylesheet" defer="">
    <link href="http://test.test/vendor/moonshine/assets/minimalistic.css?v=3.9999999.9999999.9999999-dev" rel="stylesheet" defer="">


```

### Steps To Reproduce

выше.

**Comment by lee-to** [comment]
1) Вообще сейчас это выглядит так - сперва ресурс добавляет ассеты а потом (всегда последним) грузится шаблон который добавляет свои ассеты, что говорит о том что ассеты шаблона всегда будут в конце

2) Не нужно использовать getAssets у ресурса, единственное место где он требуется это Fields, да и зачем каждый раз их там держать когда есть метод   onLoad чтобы добавить их когда ресурс или страница активны

```php
protected function onLoad(): void
{
    $this->getAssetManager()->add(InlineJs::make('alert(1)'));
}
```

4) Что касается жизненого цикла то я добавлю в ассет менеджер три метода append, prepend

Issue не закрывай, я закрою когда сделаю 4

**Comment by ArtemYurov** [comment]
1. Ну так иногда нужно же переопределить стандартный дизайн. Поэтому хотелось бы чтобы ассеты были после шаблона
2. Я согласен что не нужно, но это рекомендация ваша же из тг чата)) окей значит об assetManager нужно упомянуть в доке.

**Comment by lee-to** [comment]
> 1. Ну так иногда нужно же переопределить стандартный дизайн. Поэтому хотелось бы чтобы ассеты были после шаблона
> 2. Я согласен что не нужно, но это рекомендация ваша же из тг чата)) окей значит об assetManager нужно упомянуть в доке.

1. А почему тогда не переопределять в шаблоне? Там есть метод с ассетами, ставьте как требуется, зачем это делать через сахар для ленивых (ну и новые методы решат в любом случае эту задачу)
2. Мы еще не писали в доке про ассет менеджер поэтому тема не раскрыта

**Comment by ArtemYurov** [comment]
1. Так зачем мне переопределять во всём шаблоне, если мне нужно только на одной странице например изменить высоту таблицы?

**Comment by lee-to** [comment]
> 1. Так зачем мне переопределять во всём шаблоне, если мне нужно только на одной странице например изменить высоту таблицы?

Ждать когда я добавлю методы append/prepend и сделать

$this->assetManager()->prepend()

**Comment by lee-to** [comment]
#1352

**Comment by ArtemYurov** [comment]
Так, ещё до кучи про компоненты - там же тогда тоже нужно prepend. Сейчас есть trait WithAssets. Там есть методы:

```
    public function addAssets(array $assets): static
    {
        $this->getAssetManager()->add($assets);

        return $this;
    }

    public function pushAssets(array $assets): static
    {
        $this->assets = array_merge($this->assets, $assets);

        return $this;
    }
```

**Comment by lee-to** [comment]
Множество изменений, в том числе и ломающих совместимость описал в доке

https://github.com/moonshine-software/doc/commit/ed98d4613baa0bd47361693e0d7b27d82082d13f

**Comment by ArtemYurov** [comment]
у меня был такой код в ресурсе:
```
    protected function onLoad(): void
    {
        $this->getIndexPage()->pushToLayer(
            layer: Layer::TOP,
            component: Fragment::make([
            ....
            ])->name('metrics2')
            ->addAssets([InlineCss::make("
                .box-shadow:before {
                    display: none
                }
            ")]),
        );

    }
```

сейчас этот assets перестал добавляться. И я правильно понял доку что в этом случае на лету у нас должно быть такое же поведение:
_Метод add будет зависеть от жизненного цикла приложения._
