### ISSUE TITLE
[3.x] Передача параметров запроса при асинхронном обновлении

### ISSUE THREAD

**Issue by ArtemYurov** [moonshine-software/moonshine#1347]
### MoonShine Version

3.x-dev 856a134

### Laravel Version

11.34.2

### PHP Version

8.3.12

### Description

Если мы открываем page и передаём параметры в запрос (например id)
То после вызова event на обновление эти параметры не передаются:
![telegram-cloud-photo-size-2-5474521322034945779-x](https://github.com/user-attachments/assets/71826ad8-9b8c-4681-98fe-c9195eb56e54)

### Steps To Reproduce

при вызове event на обновление

**Comment by lee-to** [comment]
а я добавил фичи на этот счет https://github.com/moonshine-software/doc/blob/3.x/ru/components/fragment.md#параметры-запроса-url

**Comment by ArtemYurov** [comment]
А для таблицы тоже такое доступно?

**Comment by lee-to** [comment]
С этим потом, как появятся желающие после релиза, сделаем голосование при наличии четко сформированного кейса
