### ISSUE TITLE
[3.x] modelResource Ломается верстка если обернуть метрики во фрагмент

### ISSUE THREAD

**Issue by ArtemYurov** [moonshine-software/moonshine#1348]
### MoonShine Version

3.x-dev 856a134

### Laravel Version

11.34.2

### PHP Version

8.3.12

### Description

По мотивам https://t.me/moonshine_ru/6/13050

Верстка без использования фрагмента
<img width="739" alt="image" src="https://github.com/user-attachments/assets/6545445f-3307-454b-b0ea-cba5beb4bf08">

Верстка с фрагментом
<img width="462" alt="image" src="https://github.com/user-attachments/assets/b1f101a2-adf2-4c5a-b72d-1827bf6579a3">

Вообще пожелание сделать по умолчанию фрагмент метрик с каким нибудь методом для получения его имени для события обновления

### Steps To Reproduce

```
    protected function metrics(): array
    {
        return [
            Fragment::make([
                Column::make([
                    ValueMetric::make('Тест')
                        ->value(100)
                ])->columnSpan(3),
                Column::make([
                    ValueMetric::make('Тест')
                        ->value(100)
                ])->columnSpan(3),
            ])->name('metrics')
        ];
    }
```

**Comment by lee-to** [comment]
А где в примере Grid? без Grid же Column будут разваливаться

**Comment by ArtemYurov** [comment]
точно. но проблему это решает. вот с grid

<img width="509" alt="image" src="https://github.com/user-attachments/assets/a10a78f0-5d1e-4711-85e6-d555f420af47">

**Comment by lee-to** [comment]
> точно. но проблему это решает. вот с grid
> 
> <img alt="image" width="509" src="https://private-user-images.githubusercontent.com/13986502/390836390-a10a78f0-5d1e-4711-85e6-d555f420af47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MDc4NjMsIm5iZiI6MTczMjgwNzU2MywicGF0aCI6Ii8xMzk4NjUwMi8zOTA4MzYzOTAtYTEwYTc4ZjAtNWQxZS00NzExLTg1ZTYtZDU1NWY0MjBhZjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDE1MjYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5OGEyNGVmNDBjMzdkYmJjNDA2YTkzM2M4YzI1YTYyY2NhMGMzNmQ5ZWJmMDQ5YzkwZDBkZjM3YWNkMDM5ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.whTALOW0yIXbhAfd8a4y1qUQko5YnNjMYq-WOPM5o0E">

Да там шаблон прям под метрики, чтобы не юзать колумны и гриды, получается сейчас нужно через компоненты страницы такое выводить а не через область метрик

**Comment by lee-to** [comment]
Или убрать готовые стили с флексами под метрики и дать возможность самим указывать гриды и колумны, но усложнит добавление метрик, сейчас этот блок для быстрого добавления только метрик без лишних компонентов. Вообщем надо подумать

**Comment by ArtemYurov** [comment]
ну я у себя добавил метрики с фрагментом в topLayer

но идея обновлять стоковые метрики по событию возникла не только у меня одного, поэтому issue

**Comment by lee-to** [comment]
https://github.com/moonshine-software/moonshine/pull/1354
