### ISSUE TITLE
change the import or export implementation isn't working

### ISSUE THREAD

**Issue by Luisby47** [moonshine-software/moonshine#1351]
### MoonShine Version
2.23.2

### Laravel Version
11.34.2

### PHP Version
8.2

### My code:
I generated a custom Import equal to ImportHandler of Moonshine, I just changed the label of toast.

```
   public function import(): ?ImportHandler
    {
        return CustomImportHandler::make("Importar");
    }
```
    
    
The error:

App\MoonShine\Resources\CrnubeSpreedsheatConceptosResource::import(): Return value must be of type ?MoonShine\Handlers\ImportHandler, App\MoonShine\Handlers\CustomImportHandler returned_

**Comment by lee-to** [comment]
Your custom import should inherit ImportHandler and override what you need inside
