### ISSUE TITLE
[3.x] Fragment::async ?

### ISSUE THREAD

**Issue by ArtemYurov** [moonshine-software/moonshine#1357]
### Description

У фрагмента вызов событий осуществляется через updateWith, тогда как у остальных компонентов через async.

Не является ли это разногласием в логике?
По привычке написал для фрагмента ->async(events: ...) и начал разбираться почему он не работает (если так написать, то вообще перестаёт  работать обновление фрагмента) 

в 2 доке упопинается метод updateAsync с указанием resourceItem, но по доке 2/3 совершенно непонятно зачем это нужно.

**Comment by ArtemYurov** [comment]
ну и до кучи, будет ли уместно также добавить ->whenAsync  для идентичности с tableBuilder? 
но, конечно, можно добавить в доку и так: ->when(request('_fragment-load') === 'fragment-name',...

**Comment by lee-to** [comment]
Fragment по умолчанию в констракте асинк, поэтому чтобы его дополнять  нужны другие методы, хочется асинк ну тогда будь добр и урл задать)

**Comment by lee-to** [comment]
Фичи до релиза и обработки багов 3.0 приниматься и рассматриваться не будут

**Comment by ArtemYurov** [comment]
> Фичи до релиза и обработки багов 3.0 приниматься и рассматриваться не будут

Все ок. Просто вопрос про логичное наименование функций в общем стиле чтобы вдруг потом не переименовывать

**Comment by lee-to** [comment]
> > Фичи до релиза и обработки багов 3.0 приниматься и рассматриваться не будут
> 
> 
> 
> Все ок. Просто вопрос про логичное наименование функций в общем стиле чтобы вдруг потом не переименовывать 

Уже поздно переименовывать в любом случае, но с фрагментом на мой взгляд все хорошо
