### ISSUE TITLE
Error in asynchronous form submission via ActionButton event call

### ISSUE THREAD

**Issue by Reker7** [moonshine-software/moonshine#1359]
### MoonShine Version

3.0.0-rc.1

### Laravel Version

11.34.2

### PHP Version

8.4.1

### Database Driver & Version

MySQL 8.0.31

### Description

When trying to send async form via button with JsEvent::FORM_SUBMIT event call, the sending is not asynchronous

### Steps To Reproduce

```
ActionButton::make('Добавить в поставку')
->method('test', events: [AlpineJs::event(JsEvent::FORM_SUBMIT, 'async-form')]),

FormBuilder::make(route('test'))
    ->name('async-form')
    ->async()
    ->submit(label: '', attributes: ['class' => 'hidden'])
    ->fields([
        Text::make('Title')
    ])

**Comment by lee-to** [comment]
Hello my friend! I checked it in my dev branch (maybe we already fixed it) and I didn't find any problems, first the request flew to the test method and then the asynchronous one flew to the form. Possible problems you have:
1. The test method returned 500
2. Something else breaks the client part

Also, perhaps the dispatchEvent method would suit you better
