### ISSUE TITLE
[3.x] Слипаются бейджи по вертикали

### ISSUE THREAD

**Issue by shevl-dev** [moonshine-software/moonshine#1365]
### Description

Заметил, что у бейджей стоит класс 'm-1' но в бандле его нет, видимо достаточно будет пересобрать статику:
![image](https://github.com/user-attachments/assets/7551f10e-26d5-472d-8282-31c4beaf418a)

**Comment by lee-to** [comment]
Указывайте версию в задачах

**Comment by lee-to** [comment]
Пофиксил, скоро соберу патч
