### ISSUE TITLE
[3.x] Слишком узкая колонка с заголовками полей ресурса в модалке при $detailInModal = true

### ISSUE THREAD

**Issue by shevl-dev** [moonshine-software/moonshine#1366]
### Description

Кажется узковата колонка, если не ошибаюсь раньше она была шире.
Ну или возможно стоит саму модалку по шире сделать на десктопе.
![image](https://github.com/user-attachments/assets/46f23aa4-e2a1-4068-8f27-ac4b253648f7)

![image](https://github.com/user-attachments/assets/510c757e-fdbb-42a7-8a8d-5cc29cceef67)

**Comment by lee-to** [comment]
Указывайте версию в issue

**Comment by lee-to** [comment]
Я понял почему ты такое спросил, потому что я не написал это в доке( Пошел писать а пока скину решение и сюда

```php
/** @param TableBuilder $component */
public function modifyDetailComponent(ComponentContract $component): ComponentContract
{
    return $component->vertical(
        title: fn(FieldContract $field, Column $default, TableBuilder $ctx) => $default->columnSpan(2),
        value: fn(FieldContract $field, Column $default, TableBuilder $ctx) => $default->columnSpan(10),
    );
}
```

**Comment by ichinya** [comment]
Если указать оба по 12, то заголовок будет над значением
