### ISSUE TITLE
[3.x] кнопки в индексной таблице переносятся на другую строку

### ISSUE THREAD

**Issue by shevl-dev** [moonshine-software/moonshine#1371]
### Description

Думаю, зря добавили класс `flex-wrap` блоку с кнопками, раньше даже при большом количестве полей появлялся горизонтальный скролл, но кнопки всё равно оставались в 1 ряд:

![image](https://github.com/user-attachments/assets/29aaaf67-003b-413c-ad32-5f10cb3f218c)

**Comment by shevl-dev** [comment]
Я уже отправил [pr](https://github.com/moonshine-software/moonshine/pull/1372) )

**Comment by lee-to** [comment]
> Я уже отправил [pr](https://github.com/moonshine-software/moonshine/pull/1372) )

Знаю но не факт что он пройдет
