### ISSUE TITLE
[3.x] При переключении светлой\темной темы в левой колонке меняется только цвет логина в профиле

### ISSUE THREAD

**Issue by shevl-dev** [moonshine-software/moonshine#1374]
### Description

![image](https://github.com/user-attachments/assets/5dec7289-3e22-437c-9000-83436ea9d65d)
![image](https://github.com/user-attachments/assets/272404a1-9379-47d0-90d4-c5a39ec896af)

**Comment by lee-to** [comment]
так в основной же теме сайдбар всегда такой был

**Comment by shevl-dev** [comment]
> так в основной же теме сайдбар всегда такой был

Возможно, не помню, но странно почему именно логин меняет цвет? почему тогда и цвет имени не менять и в целом цвет всего текста в сайдбаре?
