### ISSUE TITLE
[2.x-3.x] Отступы между form-group

### ISSUE THREAD

**Issue by shevl-dev** [moonshine-software/moonshine#1379]
### Description

В main.css имеется такой селектор:
```
.form-group+.form-group {
    margin-bottom: 1.25rem;
    margin-top: 1.25rem;
}
```

Если идет несколько полей подряд, то всё норм, но если я делаю грид по одному полю в каждой колонке, то отступов по вертикали нет вообще и грид прилипает к следующему за ним блоку. Даже если за гридом идёт обычное поле без обертки типа Grid или Box, оно всё равно не имеет отступа, т.к. селектор добавляет отступы только когда поле идет после такого же поля.

Можно, конечно, воткнуть какие-то стили через customAttributes, но хотел убедиться, что это не косяк в верстке :)

В целом странная логика, если например идёт 2 и более полей, потом какой-то декор, то всё норм, но если сделать одно поле, потом декор, то оно будет прилипать.

![image](https://github.com/user-attachments/assets/d46cba1e-898a-4eb4-a3b5-c83953a96980)

P.S. для себя я решал эту проблему добавлением Divider между группами полей.

**Comment by lee-to** [comment]
Попробуем пофиксить но ты пока вместо Divider можешь юзать LineBreak

**Comment by lee-to** [comment]
https://github.com/moonshine-software/moonshine/pull/1384 проверяй)
