### ISSUE TITLE
I made a language repo for moonshine Zh (Chinese), would you please create a repo moonshine/zh, then make a pull requests

### ISSUE THREAD

**Issue by WillieOng-HK** [moonshine-software/moonshine#1380]
### Description

The Language includes 
- Simplified Chinese (China)
- Traditional Chinese (Hong Kong)
- Traditional Chinese (Taiwan)

<img width="372" alt="image" src="https://github.com/user-attachments/assets/990a351a-5ce1-43b3-abfb-1a5c00de33a8" />

**Comment by lee-to** [comment]
Thank you!

You need to create your own repository, then create a release and publish it on [packages.org](https://packagist.org)
Here is an example
https://github.com/SchilinskiAlexander/MoonShine-German-Language

After that, go to [moonshine-laravel.com](https://moonshine-laravel.com/plugins) and click add plugin
