### ISSUE TITLE
How can I interact field values before save (Model Resource with Pages)

### ISSUE THREAD

**Issue by WillieOng-HK** [moonshine-software/moonshine#1387]
### Version
`moonshine/moonshine:"^3.0"`

### Description

I am using Model Resource with Pages, there are "config", "app_id", "app_secret" fields, which "config" set hidden, I want to combine "app_id" & "app_secret" to json and save to config field.
ps. table doesn't have "app_id" & "app_secret" fields.

```
UI\Fields\Enum::make('platform_type')
    ->attach(Enums\PlatformType::class),
UI\Fields\Hidden::make('config'),
UI\Fields\Text::make('app_id'),
UI\Fields\Text::make('app_secret'),
```

**Comment by lee-to** [comment]
This is not a task but a question, it is better to move this to discussions or to a telegram chat
