### ISSUE TITLE
[3.x] Using Json Fields and showWhen

### ISSUE THREAD

**Issue by WillieOng-HK** [moonshine-software/moonshine#1395]
### MoonShine Version

3.0

### Laravel Version

11

### PHP Version

8.2

### Database Driver & Version

MySQL 8.0

### Description

When Using showWhen inside Json Field, the `style="display: block;"` affects style

### Steps To Reproduce

```
UI\Fields\Json::make('config')
  ->fields([
      UI\Fields\Text::make('app_id')
          ->translatable($this->tranlations . 'fields'),
      UI\Fields\Text::make('app_secret')
          ->translatable($this->tranlations . 'fields'),
      UI\Fields\Text::make('token')
          ->translatable($this->tranlations . 'fields')
          ->showWhen('platform_type', Enums\PlatformType::WECHAT_OFFICIAL_ACCOUNT),
      UI\Fields\Text::make('aes_key')
          ->translatable($this->tranlations . 'fields')
          ->showWhen('platform_type', Enums\PlatformType::WECHAT_OFFICIAL_ACCOUNT),
  ])
  ->translatable($this->tranlations . 'fields')
  ->withoutWrapper(),
```
<img width="560" alt="image" src="https://github.com/user-attachments/assets/2505f276-ae15-404e-9d1d-ac08e30d7c92" />

<img width="596" alt="image" src="https://github.com/user-attachments/assets/ff8a63b1-4f71-49fe-be63-af60b01c3cdc" />

**Comment by lee-to** [comment]
You can't use showWhen like that

The method works from the form, so for json you need to specify the parent column and index in the table

```php
->showWhen('config.0.platform_type', '!=', 2)
```

value is primitive type
