### ISSUE TITLE
[3.x] Ошибка в методе $component->style([])

### ISSUE THREAD

**Issue by ckr0n** [moonshine-software/moonshine#1411]
### MoonShine Version

3.0.3

### Laravel Version

10.48.25

### PHP Version

8.2.25

### Description

Метод добавления стиля в документации описан со следующим синтаксисом:
$component->style(['color' => 'red']);
но в результате применения такого метода на выходе получается такой HTML
< ... style="color;">
если метод применить таким образом 
$component->style(['color:red']); то html будет правильный <... style="color:red;">
Данный момент нужно либо в документации исправить, либо в методе.

### Steps To Reproduce

в ресурсе Title::make('Заголовок', 6)->style(['color'=>'red'])

**Comment by DissNik** [comment]
Это не является ошибкой Moonshine, проблема в документации, сам метод работает как положено
`->style(['color: white', 'background-color: black'])`, если есть возможность, сделайте pr с исправления в документацию
