### ISSUE TITLE
Теряется поле из фрагмента при сохранении формы

### ISSUE THREAD

**Issue by ichinya** [moonshine-software/moonshine#1417]
### MoonShine Version

3.0.5

### Laravel Version

11.36

### PHP Version

8.2.26

### Database Driver & Version

MySQL 8.0.22

### Description

Заметил странное поведение при сохранении ресурса. При сохранении в модели не сохранялось одно поле. В fillable оно было указано, Field был на форме. В request после нажатия оно было, но его не было перед сохранением модели в базу.

### Steps To Reproduce

Форма в ресурсе, если есть доп поля, они выводятся в json, а если их нет, то скрытое поле (для сохранения и валидации):
```php
 public function formFields(): array
    {
        $request = MoonShineRequest()->get('_data');
// .. skip
        $configFields = $botInstance->getConfigFields();
        if ($configFields) {
            $fields[] = Json::make('', 'config')->fields($configFields)->object();
        } else {
            $fields[] = Hidden::make('Конфигурация', 'config');
        }
// .. skip
        return [
            Fragment::make($fields)->name('form-fragment'),
        ];
    }
```

Правила:
```php
  public function rules($item): array
    {
        return [
            'config' => ['nullable', 'array'],
        ];
    }

Модель:
```php
class Bot extends Model
{
    protected $fillable = ['name', 'config', 'hash']; // skip лишние поля
    protected $casts = [
        'config' => 'array',
    ];
}
```

Поле **config** не сохранялось.

Решение получилось странное, пришлось добавить поле:

```php
 public function prepareForValidation(): void
    {
        $request = MoonShineRequest();
         request()?->merge([
            'config' => $request['config'] ?? [], 
        ]);
// dump(request());
}
```

При этом если проверить до и после вывод dump request был одинаковый

**Comment by lee-to** [comment]
залогируйте вот if ($configFields) , точно ли оно всегда true

**Comment by ichinya** [comment]
![image](https://github.com/user-attachments/assets/fa18c281-3588-416e-a192-3f3aa703bf2d)
![image](https://github.com/user-attachments/assets/e7bf13e9-064e-44c3-b814-8e578e907d65)


При выборе Select обновляется Fragment, в котором разные поля из конфига берутся

**Comment by lee-to** [comment]
Ну значит при реквесте на сохранение он false и поэтому не сохраняется, так как его нет в полях

**Comment by lee-to** [comment]
Фрагмент не скипает поля, у нас по дефолту в коробке много мест обвернутых фрагментом

**Comment by ichinya** [comment]
> Ну значит при реквесте на сохранение он false и поэтому не сохраняется, так как его нет в полях

В условии если false, то создается поле в форму 
` $fields[] = Hidden::make('Конфигурация', 'config');`

Если смотреть в  `public function prepareForValidation(): void`, то оно передается, а перед сохранением где идёт перебор Fields, его уже нет.

**Comment by lee-to** [comment]
Воспроизвел у себя кейс
```php
protected function formFields(): iterable
    {
        $fields = [];

        if(true) {
            $fields[] = Text::make(__('moonshine::ui.resource.role_name'), 'name')
                ->required();
        }

        return [
            Box::make([
                ID::make()->sortable(),
                Fragment::make($fields)
            ]),
        ];
    }
```

Проблем нет и поле всегда присутствует, здесь именно проблема где то у вас в логике, либо вы предоставляете не тот кейс для проверки, сейчас я воспроизвести проблему не могу, поэтому issue вынужден закрыть
