### ISSUE TITLE
Ошибка в методе ->copy()

### ISSUE THREAD

**Issue by Sanes** [moonshine-software/moonshine#242]
### MoonShine Version

1.55.2

### Laravel Version

10.9.0

### PHP Version

8.1

### Database Driver & Version

8.0

### Description

Имеется такая конструкция
```
Text::make('Пароль пользователя', 'password')->required()->default(Str::random(10))->eye()->copy();
```
При клике на кнопку копирования в консоле и фактически копирование не выполняется.
```
Uncaught TypeError: navigator.clipboard is undefined
```
Тоже самое с полем Password

**Comment by lee-to** [comment]
Нельзя копировать у элементов type hidden

**Comment by Sanes** [comment]
Попробовал использовать только метод `copy()` Результат тот же.
```
Text::make('Пароль пользователя', 'password')->required()->default(Str::random(10))->copy()->hideOnIndex();
```

**Comment by DissNik** [comment]
navigator.clipboard работает вроде бы только на https или localhost
