### ISSUE TITLE
Дублирование запросов в базу данных

### ISSUE THREAD

**Issue by jstpd** [moonshine-software/moonshine#26]
Добрый день. Заметил странное поведение при выборке из базы данных. Админ панель дублирует запросы 3 раза, на всех разделах меню.
Скриншот
[https://ibb.co/F402x0v](https://ibb.co/F402x0v)
Должно быть 4 запроса в БД, а не 8.. 
При добавлении тестовой ValueMetric в место 1 запроса в БД идет 5 запросов

**Comment by lee-to** [comment]
Добрый день! Спасибо это действительно важный баг, исправил
