### ISSUE TITLE
Ошибки формата JSON

### ISSUE THREAD

**Issue by jstpd** [moonshine-software/moonshine#27]
Добрый день.
Заметил ошибки при работе с _Leeto\MoonShine\Fields\Json_ 
**Json::make('Параметры', 'params')->keyValue('Характиристика', 'Значение')**
После сохранения выводит 1 поле, key = 0, value =  весь json массив строкой, в место развернутого списка.
**Json::make('Параметры', 'params')->fields([Text::make('Заголовок', 'name'), Text::make('Значение', 'value')])->removable()**
Ошибка при сохранении Array to string conversion
```
"params": [
        {
            "name": "par1",
            "value": "C25"
        },
        {
            "name": "par2",
            "value": "160"
        }
    ]
```

**Comment by lee-to** [comment]
Добрый день! Проблема в том что у вас менялась структура json поля и в итоге она не соответствует структуре в ресурсе, очистите содержимое поля json в базе и попробуйте еще раз! Я протестировал эти кейсы у себя в последней версии и ошибку не смог воспроизвести
