### ISSUE TITLE
Ошибка в BelongsTo для фильтрации/создания 

### ISSUE THREAD

**Issue by NikHalif** [moonshine-software/moonshine#33]
При попытке использования BelongsTo для генерации нового объекта или BelongsToFilter для фильтрации в версии 1.7.0 возникает ошибка:
`Call to undefined method Leeto\MoonShine\Fields\BelongsTo::isMultiple()`

Файл `vendor/lee-to/moonshine/resources/views/fields/multi-select.blade.php`
Строка 3:
`x-model="{{ $field->isMultiple() ? 'selectValues' : 'selectValue' }}"`

В документации или информации релиза не указаны изменения в данных параметрах. Полный вывод ошибки: 
[result.zip](https://github.com/lee-to/moonshine/files/9487966/result.zip)

**Comment by lee-to** [comment]
Спасибо за фидбек, выявил проблему и исправил в версии 1.7.1 
Но хочу обратить внимание - belongsTo не может быть multiple это исключено! Если вам нужно выбирать несколько значений тогда вам следует использовать другое laravel отношение (belongsTo подразумевает одну запись)
А вот в belongsToFilter множественное значение возможно и здесь проблема исправлена
