### ISSUE TITLE
($id) must be of type ?int, string given

### ISSUE THREAD

**Issue by AkostDev** [moonshine-software/moonshine#34]
У eloquent модели установлен тип для _primary_key_ - **string** (уникальный символьный код).
При создании ресурса для этой модели, в методе **fields** возвращается массив, в котором есть:
`ID::make()`

Как в ресурсе указать, что модель имеет primary_key типа string?

**Comment by AkostDev** [comment]
Как фикс, добавил метод **route** в свой ресурс и второму параметру добавил тип **string**

![image](https://user-images.githubusercontent.com/11013417/189146755-3f2cb1d1-a246-4277-97e9-f4ae3352ec75.png)

**Comment by lee-to** [comment]
Исправлено в версии 1.7.2! Спасибо
