### ISSUE TITLE
Кастомный путь до ресурс контроллера

### ISSUE THREAD

**Issue by rybkinevg** [moonshine-software/moonshine#35]
Привет!

Хотел бы сказать огромное спасибо за такой крутой проект, которым поделилось коммьюнити **CutCode**!

Я не очень опытный в Laravel, и после прихода с Magento, где использовался модульный подход к разработке, я решил поискать решение для внедрения модульности в Laravel и нашел отличную [библиотеку](https://github.com/nWidart/laravel-modules).

В чём заключается проблема:

Библиотека, что я упомянул, позволяет внедрить модульную архитектуру, соотвественно, у каждого модуля своя папка и подпапки для контроллеров, моделей и тд.

<img width="778" alt="image" src="https://user-images.githubusercontent.com/42123286/191100677-1673339e-13b9-4e83-b09e-d70f8f436a2e.png">

Но вот незадача, контроллер, созданный для того, чтобы отображать сущность MoonShine не может отработать, так как стоит жесткая привязка по неймспейсу контроллеров: [ссылка](https://github.com/lee-to/moonshine/blob/1.x/src/Http/Controllers/MoonShineResourceController.php#L16)

В связи с чем, я немного поменял работу этого контроллера таким образом, чтобы он определял путь до контроллера на основе ресурсов, зарегистрированных в MoonShine:

![code](https://user-images.githubusercontent.com/42123286/191101731-2c6234c0-fe14-4f5d-ab47-b4407fcb15aa.png)

В прошлых версиях, насколько я понял, можно было менять неймспейс и директорию контроллеров, но, судя по всему, в новых версиях это выпилено:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/42123286/191105096-dfb21c4b-f143-4f54-ae7f-cea75bbf1b02.png">

Решение, наверняка, довольно грязное, но, может быть кому-то пригодится, если в дальнейшем не будет какого то хака, чтобы менять дефолтный неймспейс ресурс контроллеров.

**Comment by lee-to** [comment]
Привет! Спасибо за добрые слова! Вернул возможность кастомизировать пути через конфиг в версии 1.9.2
