### ISSUE TITLE
Баг с экспортом ссылок

### ISSUE THREAD

**Issue by IgorPetrovPRO** [moonshine-software/moonshine#365]
### MoonShine Version

1.60.2

### Laravel Version

10.14.1

### PHP Version

8.2

### Description

При экспорте, если в списке есть ссылка, то в экспорт она попадает вместе svg иконкой https://disk.yandex.ru/d/41lQBlzy1ABi8w 

### Steps To Reproduce

Создать любое поле типа URL и экспортировать его

**Comment by lee-to** [comment]
Исправлено в релизе https://github.com/moonshine-software/moonshine/releases/tag/1.60.3
