### ISSUE TITLE
Ошибка вывода BelongsToMany в формате inline

### ISSUE THREAD

**Issue by IgorPetrovPRO** [moonshine-software/moonshine#373]
### MoonShine Version

1.60.4

### Laravel Version

10

### PHP Version

8.2.4

### Description

Связь BelongsToMany перестало верно выводить в формате тегов https://disk.yandex.ru/d/JqVpY_QLKeH7AA

### Steps To Reproduce

```
  BelongsToMany::make('Медицинские профили', 'medicalProfiles', 'name')
      ->inLine(separator: ' ', badge: true)
      ->select()
      ->showOnExport(),
```

**Comment by lee-to** [comment]
Исправил в релизе https://github.com/moonshine-software/moonshine/releases/tag/1.60.5
