### ISSUE TITLE
modal in resourceMode

### ISSUE THREAD

**Issue by IgorPetrovPRO** [moonshine-software/moonshine#379]
### MoonShine Version

1.60.5

### Laravel Version

10

### PHP Version

8.2

### Description

При выводе через resourceMode редактирование всегда открывается во всплывающее окно, даже при указание 
`protected bool $editInModal = false; `

### Steps To Reproduce

Создать любой ресурс вывести в него например 
```
HasMany::make('КСГ', 'clinicUseKsg', new ClinicUseKsgResource())
    ->hideOnIndex()
    ->resourceMode(),
```

**Comment by lee-to** [comment]
Ресурс мод всегда в модальном окне, поведение изменить нельзя
