### ISSUE TITLE
Баг в методе showWhen

### ISSUE THREAD

**Issue by z-takaev** [moonshine-software/moonshine#393]
### MoonShine Version

1.60

### Laravel Version

10.10

### PHP Version

8.1

### Description

При скрытии поля остается label и подсказка

### Steps To Reproduce

<img width="633" alt="Снимок экрана 2023-07-15 в 13 43 40" src="https://github.com/moonshine-software/moonshine/assets/104326716/11a6d813-013c-447f-8179-aab21a2fb325">

**Comment by YouMixx** [comment]
Привет. Вроде как проблема не со всеми полями.
С каким полем проблема у тебя?

**Comment by lee-to** [comment]
https://github.com/moonshine-software/moonshine/pull/402 fixed
