### ISSUE TITLE
Проблема с отображением содержимого в поле Code

### ISSUE THREAD

**Issue by z-takaev** [moonshine-software/moonshine#394]
### MoonShine Version

1.60

### Laravel Version

10.10

### PHP Version

9.1

### Description

Обрезается текст при боковом скролле внутри поля

### Steps To Reproduce

<img width="1073" alt="Снимок экрана 2023-07-16 в 15 08 07" src="https://github.com/moonshine-software/moonshine/assets/104326716/771f0635-6242-4b23-92df-0315ff1e6ec8">
<img width="1073" alt="Снимок экрана 2023-07-16 в 15 08 16" src="https://github.com/moonshine-software/moonshine/assets/104326716/faf9246c-774a-419a-b63b-e1610a286082">

**Comment by YouMixx** [comment]
Эта проблема не в MoonShine, а в модуле CodeFlask.
Я нашел у них issue (https://github.com/kazzkiq/CodeFlask/issues/69), в котором эту проблему решил пользователь под ником [acarl005](https://github.com/acarl005). Он предложил использовать его форк, где это исправленно.

Учитывая то, что модуль CodeFlask последний раз обновлялся в 2020 коду, я думаю можно использовать его форк.

p.s. я это написал для разрабов муншайна, посмотрим что они решат.

**Comment by DissNik** [comment]
Спасибо за наводку! 
Проблему решил, но автор форка предлагает дополнительные исправления, например с табами, нужно погонять, может быть действительно использовать его.
