### ISSUE TITLE
метод withConfirm в классе Action

### ISSUE THREAD

**Issue by VladimirVagner** [moonshine-software/moonshine#397]
### MoonShine Version

1.60.5

### Laravel Version

10.15.0

### PHP Version

8.2.7

### Description

На данный момент метод withConfirm существует только в классе ResourceAction, предлагаю метод так же добавить в класс Action. С учетом что в документации указано, что метод существует

### Steps To Reproduce

  Прописать в ресурсе
`public function actions(): array
    {
        return [
            ExportAction::make('Экспорт')->withConfirm(),
        ];
    }`

**Comment by lee-to** [comment]
Документацию поправим, у Action этого метода нет, у Action есть вьюхи которые можно без труда обвернуть в модалки
