### ISSUE TITLE
Select - не дает выбрать значение с первого раза, если он внутри Json

### ISSUE THREAD

**Issue by YouMixx** [moonshine-software/moonshine#404]
### MoonShine Version

1.60.4

### Laravel Version

10.13.5

### PHP Version

8.1.9

### Description

Если Select находится внутри Json (т.е. как option), при первом выборе элемента значение не ставится.
Приходится выбирать его по два раза.
https://disk.yandex.ru/i/JGErOuK-kyHI5g

### Steps To Reproduce

```php
Json::make(
        'Товары',
        'products'
    )
        ->fields([
            Select::make(
                'Название товара',
                'id',
            )
                ->options(['test1', 'test2', 'test3', 'test4'])
                ->searchable()
                ->required(),
        ])
        ->removable()
        ->sortable()
        ->required()
        ->fullPage()
        ->fieldContainer()
        ->hideOnIndex(),
```

**Comment by lee-to** [comment]
Не смог воспроизвести у себя, пробовал тот же самый пример что ты привел и в ресурсе и в ресурс моде!
Возможно какое то поле конфликтует о котором не сказано в описании к этому issue, либо выполнена кастомизация

**Comment by YouMixx** [comment]
Походу конфликт ключей полей.
У меня ключ у поля - id, если меняю например на ids проблемы нет.

**Comment by lee-to** [comment]
id зарезервировано в table fields под ключ, нужно использовать другое название поля

**Comment by YouMixx** [comment]
Может быть в table fields к id приписывать что-то еще? Дабы можно было использовать любой ключ.

**Comment by YouMixx** [comment]
Не могу найти в чем проблема, но баг присутствует и в том случае, если заменить id на что-то другое.
Но в этом случае, он проявляется только при редактировании записи, а при создании пропадает.
