### ISSUE TITLE
Ошибка при HasManyThrough

### ISSUE THREAD

**Issue by k-rustemuly** [moonshine-software/moonshine#451]
### MoonShine Version

1.61

### Laravel Version

10.10

### PHP Version

8.1

### Description

```
class OrganizationBookResource extends SingletonResource
{
	public static string $model = Organization::class;

	public static string $title = 'OrganizationBook';

    public static array $activeActions = ['show'];

    public static array $with = ['books'];

    public function getId(): int|string
    {
        $admin = session('selected_admin');
        return $admin ? $admin->organization_id : 0;
    }

	public function fields(): array
	{
		return [
            HasManyThrough::make('Books', 'books', new BookResource())
                ->resourceMode()
        ];
	}

	public function rules(Model $item): array
    {
        return [];
    }
}
```
В таком виде при использовании HasManyThrough дает ошибку. А именно:
Route [moonshine.organizationBooks.relation-field-form] not defined.
И добавить в
```
public function performOrder(Builder $query, string $column, string $direction): Builder
    {
        return $query->orderBy(
            **$this->getModel()->getTable()**.'.'.$column,
            $direction
        );
    }
```
Потому что при Join выдает ошибку
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in order clause is ambiguous (Connection: mysql, SQL: select * from `books` inner join `organization_books` on `organization_books`.`book_id` = `books`.`id` where `organization_books`.`organization_id` = 1 order by `id` desc limit 25 offset 0)

### Steps To Reproduce

просто можете повторить мой код

**Comment by k-rustemuly** [comment]
Не смог пофиксить

**Comment by bblbbl** [comment]
Это можно поправить переопределением метода getKey в модели, добавив имя таблицы перед перед именем идентификатора
