### ISSUE TITLE
Ошибка при нажатии "Создать" если есть Image и используется s3 для хранения

### ISSUE THREAD

**Issue by good1hare** [moonshine-software/moonshine#457]
### MoonShine Version

1.62.0

### Laravel Version

9.52.9

### PHP Version

8.1

### Database Driver & Version

MariaDB ver. 10.11.2

### Description

Когда нажимаю "Создать" выходит ошибка(ниже), если скрыть(hideOnCreate) то ошибки нет. Когда disk был public работало нормально, после перехода на s3(minIO) началась ошибка.
Проверял, все работает как нужно и картинки в админке тоже показываются:
$imagePath = 'message_images/nyan-cat-artoctober.png';
        $imageContents = Storage::disk('s3')->get($imagePath, ['pathStyle' => true]);
        $filename = Str::random(10) . '.png'; // Генерация случайного имени файла
        Storage::disk('local')->put($filename, $imageContents);

Если перед тем как нажать "Создать" закомментировать 3 строчки:
 ->dir('message_images')
                        ->disk('s3')
                        ->allowedExtensions(['jpg', 'png', 'gif'])
и потом разкомментировать то картинки сохраняются на s3 и на главной картинки тоже нормально показываются.

Ошибка:
Found 1 error while validating the input provided for the GetObject operation:
[Key] expected string length to be >= 1, but found string length of 0 (View: /var/www/vendor/moonshine/moonshine/resources/views/fields/image.blade.php) (View: /var/www/vendor/moonshine/moonshine/resources/views/fields/image.blade.php) (View: /var/www/vendor/moonshine/moonshine/resources/views/fields/image.blade.php) (View: /var/www/vendor/moonshine/moonshine/resources/views/fields/image.blade.php) (View: /var/www/vendor/moonshine/moonshine/resources/views/fields/image.blade.php) (View: /var/www/vendor/moonshine/moonshine/resources/views/fields/image.blade.php)

### Steps To Reproduce

Написать в resourse
  public function fields(): array
    {
        return [
            Tabs::make([
                Tab::make('Основное', [
                    ID::make()->sortable(),
                    Text::make('Основной текст', 'text')->required(),
                    Image::make('Вложенная картинка', 'image_url')
                        ->dir('message_images')
                        ->disk('s3')
                        ->allowedExtensions(['jpg', 'png', 'gif'])
                ]),
Настроить s3
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=
AWS_BUCKET=
AWS_ENDPOINT=https://
AWS_USE_PATH_STYLE_ENDPOINT=true

**Comment by DissNik** [comment]
Попробуйте в .env прописать AWS_URL

**Comment by good1hare** [comment]
AWS_URL помогло
