### ISSUE TITLE
The MoonShine\Exceptions\MoonShineNotFoundException is raised if you send a link to the resource to Telegram. 

### ISSUE THREAD

**Issue by Opekunov** [moonshine-software/moonshine#499]
### MoonShine Version

1.61.3

### Laravel Version

10.20

### PHP Version

8.1

### Description

If you send a link to a resource like `moonshine/resource/user-resource` to Telegram, Moonshine throws a 404 error. This is not a critical error, but you can seriously burden someone else's admin with logging :) This error is created by Telegram parser to generate a preview link.

From sentry:
```
MoonShine\Exceptions\MoonShineNotFoundException
browser.name [TelegramBot]
device [Desktop]
device.family [Spider]
environment [production]
handled [yes]
level [error]
logger [php]
mechanism [generic]
os [Linux 5.15.0-79-generic]

Accept | text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
-- | --
Accept-Encoding | deflate, gzip, br
Accept-Language | en-US,en;q=0.5
Cookie | [Filtered]
User-Agent | TelegramBot (like TwitterBot)


```

### Steps To Reproduce

Send link like `moonshine/resource/user-resource` to telegram chat

**Comment by lee-to** [comment]
Надо будет глянуть
