### ISSUE TITLE
fields incorrect

### ISSUE THREAD

**Issue by sashagm** [moonshine-software/moonshine#504]
### MoonShine Version

2.0.0

### Laravel Version

v10.25.2

### PHP Version

8,1,9

### Database Driver & Version

MariaDB 10.4

### Description

use MoonShine\Fields\SwitchBoolean;
use MoonShine\Fields\File;

При использование ломаются поля:

SwitchBoolean - В просмотре/редактирование всегда значение false. Если обновить запись он так же записывается в false даже если true,

File - Все работает но.... Если оставить пустым в просмотре отображается ссылка типа http://localhost/storage/files/[] хотелось бы скрыть этот момент не учитывать если null/ []

### Steps To Reproduce

SwitchBoolean::make('Опубликовать', 'status')
                        ->onValue(1) 
                        ->offValue(0) ,

File::make('File', 'file')
                        ->dir('/files') // Директория где будут хранится файлы в storage (по умолчанию /)
                        ->disk('public') // Filesystems disk
                        ->allowedExtensions(['jpg', 'gif', 'png']) // Допустимые расширения
                        ->multiple()
                        ->removable(),
                        
     $table->json('file')->nullable();

**Comment by DissNik** [comment]
SwitchBoolean нет такого поля. У вас точно альфа?

**Comment by DissNik** [comment]
SwitchBoolean  оказывается еще есть в альфе :). Повторить вашу ситуацию не удалось, поле работает.

**Comment by DissNik** [comment]
Такое поведение поля File, если нет каста у модели

```
protected $casts = [
    'files' => 'collection',
];
```

**Comment by sashagm** [comment]
> Такое поведение поля File, если нет каста у модели
> 
> ```
> protected $casts = [
>     'files' => 'collection',
> ];
> ```

попробую добавить, а версия да альфа

**Comment by sashagm** [comment]
> SwitchBoolean оказывается еще есть в альфе :). Повторить вашу ситуацию не удалось, поле работает.

поле то работает исправно, переключается и сохраняется. но если перейдите в редактирование записи по дефолту стоит 0/false а не значение записи ( тут либо просто дефолт либо нет проверки на существование или не передано значение)

**Comment by lee-to** [comment]
Не пойму есть в итоге проблема или нет?

**Comment by sashagm** [comment]
> Не пойму есть в итоге проблема или нет?

попозже проверю, комп далеко
