### ISSUE TITLE
moonshine:layout

### ISSUE THREAD

**Issue by sashagm** [moonshine-software/moonshine#552]
### MoonShine Version

2.0.0 alfa 3

### Laravel Version

10.28

### PHP Version

8,1,9

### Database Driver & Version

MariaDB 10.4

### Description

  ERROR  Command "moonshine:layout" is not defined. Did you mean one of these?

  ⇂ moonshine:apply
  ⇂ moonshine:component
  ⇂ moonshine:controller
  ⇂ moonshine:field
  ⇂ moonshine:install
  ⇂ moonshine:page
  ⇂ moonshine:publish
  ⇂ moonshine:resource
  ⇂ moonshine:user

### Steps To Reproduce

moonshine:layout

**Comment by DissNik** [comment]
Команда moonshine:publish позволяет опубликовать layout

**Comment by sashagm** [comment]
> Команда moonshine:publish позволяет опубликовать layout

на .3  команда не работает, либо в провайдере не видит класс

**Comment by sashagm** [comment]
Вызвать можно только так

$ php artisan moonshine:publish

  Types: [None]
  None .................................................................................................................
  Assets ........................................................................................................ assets
  Layout ........................................................................................................ layout
❯ Layout

 Layout published
