### ISSUE TITLE
ViewPage not found

### ISSUE THREAD

**Issue by sashagm** [moonshine-software/moonshine#553]
### MoonShine Version

2.0.0  alfa3

### Laravel Version

10.28

### PHP Version

8,1,9

### Database Driver & Version

MariaDB 10.4

### Description

ViewPage есть в пакете но он не докачивается, нельзя использовать, если вручную докинуть его то нормально.

### Steps To Reproduce

MenuItem::make(
    'Custom',
    ViewPage::make()
        ->setTitle('Hello')
        ->setLayout('custom_layout')
        ->setContentView('my-form', ['param' => 'value'])
),

**Comment by DissNik** [comment]
ViewPage отсутсвует, будет только в следующем релизе

**Comment by sashagm** [comment]
> ViewPage отсутсвует, будет только в следующем релизе

Ждемс) в доке уже есть, вручную нормально работает, так же в доке необходимо дописать алиас на этот код иначе на разные MenuItem на один и тот же url сток ведет

так все работает норма)

MenuItem::make(
                    'Laravel Telescope',
                    ViewPage::make()
                        ->setTitle('Laravel Telescope')
                        ->alias('tele') 
                        ->setContentView('admin.system.tele', ['param' => 'value'])
                ),
                MenuItem::make(
                    'Журнал действий',
                    ViewPage::make()
                        ->setTitle('Журнал действий')
                        ->alias('holl') 
                        ->setContentView('admin.system.holl', ['param' => 'value'])
                ),
