### ISSUE TITLE
Поле Json в режиме отношения дублирует контент в БД

### ISSUE THREAD

**Issue by rogodessa** [moonshine-software/moonshine#612]
### MoonShine Version

2.0

### Laravel Version

10.30.1

### PHP Version

8.0.1

### Database Driver & Version

MySQL 8.0.30

### Description

Здравствуйте.

При использовании field Json в режиме отношения дублирует контент в БД, в таблице отношения.
Баг или я что-то не так делаю?

Используемый код:

### Steps To Reproduce

```
Json::make('Names')
->asRelation(new NameResource())
->fields([
    Text::make('Name', 'name')->required(),
])
->creatable()
->removable()
->required()
->hideOnIndex()
```

**Comment by DissNik** [comment]
Для отношения необходим id

```
Json::make('Names')
->asRelation(new NameResource())
->fields([
    ID::make(),
    Text::make('Name', 'name')->required(),
])
->creatable()
->removable()
->required()
->hideOnIndex()
```

**Comment by rogodessa** [comment]
> Для отношения необходим id
> 
> ```
> Json::make('Names')
> ->asRelation(new NameResource())
> ->fields([
>     ID::make(),
>     Text::make('Name', 'name')->required(),
> ])
> ->creatable()
> ->removable()
> ->required()
> ->hideOnIndex()
> ```

Да, действительно. Решено ))
Спасибо!
