### ISSUE TITLE
Select::make(...)->multiplie() в HasOne

### ISSUE THREAD

**Issue by austyuzhaninov** [moonshine-software/moonshine#616]
### MoonShine Version

1.62.1

### Laravel Version

10.28.0

### PHP Version

8.2.12

### Database Driver & Version

8.0.34

### Description

Не передаётся значение поля Select::make()->multiplie() в отношении HasOne.

![image](https://github.com/moonshine-software/moonshine/assets/38152348/d4392e16-65c5-402d-83dc-7b12d3b03393)

![image](https://github.com/moonshine-software/moonshine/assets/38152348/90d249f4-2397-47c6-8d3e-ebad546815dc)

https://flareapp.io/share/x5MwVlDP

При обычном селекте Select::make() значения передаются корректно.
![image](https://github.com/moonshine-software/moonshine/assets/38152348/cc454228-4aca-418b-8bb1-cb8e9c8f6b73)

### Steps To Reproduce

- Создадим тестовую модель `php artisan make:model Test -m`
- В миграции добавим json поле:

```
public function up(): void
{
    Schema::create('tests', function (Blueprint $table) {
        $table->id();
        $table->foreignIdFor(User::class);
        $table->json('test_json_field');
        $table->timestamps();
    });
}
```

- Test Модель:

```
class Test extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'user_id',
        'test_json_field',
    ];
}
```

- Создадим ресурс `php artisan moonshine:resource TestResource` с полями

```
public function fields(): array
    {
        return [
            ID::make(),
            Select::make('test_json_field', 'test_json_field')
                ->options([1=>'Тест 1',2=>'Тест 2',3=>'Тест 3'])
                ->multiple(),
        ];
 }
```

- Добавим отношение к модели Test в модель User

```
public function test(): HasOne
{
    return $this->hasOne(Test::class);
}
```

- В ресурс пользователя UserResource добавим поле

```
HasOne::make('test', 'test', new TestResource())->fullPage()->hideOnIndex(),
```

- Пробуем создать/редактировать пользователя

**Comment by lee-to** [comment]
На поле также нужен cast collection

**Comment by austyuzhaninov** [comment]
> На поле также нужен cast collection

https://flareapp.io/share/95JweDrm

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Test extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'user_id',
        'test_json_field',
    ];

    protected $casts = [
        'test_json_field' => 'collection',
    ];
}
```
Так же пробовал в array и json

**Comment by lee-to** [comment]
`
{
    "_token": "DOfx3LYJ1z9EIzT8kf1HfZVCm6ohxY4UQLdVtZXI",
    "id": null,
    "login": "Nikola2",
    "password": "<CENSORED>",
    "password_repeat": "1",
    "fio": "Николай2",
    "email": null,
    "birthday": null,
    "phones": [
        {
            "number": "9112223344"
        }
    ],
    "test": [
        {
            "id": null
        }
    ],
    "search_terms": null
}
`

Судя по запросу его у вас вообще в теле нет, попробуйте использовать resourceMode

**Comment by austyuzhaninov** [comment]
> Судя по запросу его у вас вообще в теле нет, попробуйте использовать resourceMode

Пока ресурс мод не рассматривал как решение поставленной задачи и не особо работал с ним. Подразумевалось, что будет одна форма с которой создается пользователь + настройки к нему. Всё это через отдельные модели Пользователя и Настроек. Сначала создается пользователь, затем создаются настройки в которых участвует как user_id так и другие ключи.

Попробую разобраться почему в тело запроса он не попадает.
