### ISSUE TITLE
MorphMany

### ISSUE THREAD

**Issue by Vladsg** [moonshine-software/moonshine#62]
Не работает кнопка добавить, если редактируется ресурс с уже заполненым полем, пока не удалить заполненный элемент
![изображение](https://user-images.githubusercontent.com/19352528/209447587-4944e6b0-4e1d-4b71-bdb2-27da46c1f9d0.png)

**Comment by lee-to** [comment]
MorphMany визуально полный дубль HasMany, ошибку думаю вызывает какое то поле внутри, надо поочередно их отключать и вычислить что именно и дать мне больше информации, сейчас я проверил MorphMany на тестовых данных и все работает

**Comment by Vladsg** [comment]
Да там просто 1 текстовое поле
![изображение](https://user-images.githubusercontent.com/19352528/209477692-b4290a27-7226-446c-b8af-adaf48a27659.png)

**Comment by lee-to** [comment]
не смог воспроизвести, у меня работает, может содержимое поле тэг ломает?

**Comment by Vladsg** [comment]
хм, дейсствительно. Там вроде ничего кроме слова не было, сейчас я не могу скинуть какое оно было, т.к. бд была перезаполнена и сейчас все работает
