### ISSUE TITLE
Выборка времени в DateRange не работает

### ISSUE THREAD

**Issue by k-rustemuly** [moonshine-software/moonshine#633]
### MoonShine Version

2.0.0

### Laravel Version

10.10

### PHP Version

8.2

### Description

 DateRange::make('Dates',  'dates') не работает выборка времени при филтрации в Firefox 119.0.1
 

### Steps To Reproduce

Firefox

**Comment by lee-to** [comment]
Firefox какой? мы нативно же юзаем

**Comment by lee-to** [comment]
https://caniuse.com/?search=input%20range

**Comment by lee-to** [comment]
В фф не поддерживается нативно

**Comment by lee-to** [comment]
Вручную нужно писать
