### ISSUE TITLE
Проблема при massDelete в ModelResource

### ISSUE THREAD

**Issue by khlystou** [moonshine-software/moonshine#673]
### MoonShine Version

2.2

### Laravel Version

10.30

### PHP Version

8.1

### Description

После обновления с версии 1,5 на 2,0 перемтала появляться кнопка массделит при ручном выборе элементов
![2023-12-01_22-01-38](https://github.com/moonshine-software/moonshine/assets/17690542/d656c0bf-5b03-44ba-8d38-2e622db21d63)
При этом, если выбрать чекбокс в шапке таблицы - кнопка появляется
![2023-12-01_22-01-57](https://github.com/moonshine-software/moonshine/assets/17690542/f5eb71e5-7f3c-4652-8ad4-fda3ab60d569)
Но само удаление не работает
Попытки публикации ассетов и чистки кеша ни к чему не привели.

### Steps To Reproduce

Обновление с v1.5 до v2.0 по гайду

**Comment by lee-to** [comment]
А primary key есть в таблице?

**Comment by khlystou** [comment]
Да, так и есть. Не работает из-за отсуствия pk
