### ISSUE TITLE
Путь до логотипов

### ISSUE THREAD

**Issue by khlystou** [moonshine-software/moonshine#678]
### MoonShine Version

2,3

### Laravel Version

10,3

### PHP Version

8,2

### Description

Не верно строится путь до логотипов. Правильнее использовать``` asset(config('moonshine.logo')) ``` и ``` asset(config('moonshine.logo_small')) ``` соответственно
![image](https://github.com/moonshine-software/moonshine/assets/17690542/b34d9002-9f75-486f-80de-d8db9d4c3fab)

### Steps To Reproduce

При указание в config/moonshine.php относительного пути images/logo.svg, если URL отличается от указанного префикса, логотип не подгружается.

**Comment by khlystou** [comment]
Предлогаю использовать конструкцию ``` <img src="{{ asset(config('moonshine.logo', 'vendor/moonshine/logo.svg')) }}"> ``` и для small соответственно

**Comment by lee-to** [comment]
Ставь / и все

**Comment by lee-to** [comment]
Или полный путь если он на другом хосте

**Comment by lee-to** [comment]
> Предлогаю использовать конструкцию ``` <img src="{{ asset(config('moonshine.logo', 'vendor/moonshine/logo.svg')) }}"> ``` и для small соответственно

Добро

**Comment by lee-to** [comment]
Надо тогда еще не забыть про страницу логина

**Comment by khlystou** [comment]
https://github.com/moonshine-software/moonshine/pull/684
