### ISSUE TITLE
Баг с сортировкой

### ISSUE THREAD

**Issue by AkostDev** [moonshine-software/moonshine#695]
### MoonShine Version

2.4.0

### Laravel Version

10.34.2

### PHP Version

8.2

### Database Driver & Version

MariaDB 10

### Description

Если в ресурс добавить метод _query_, то не работает сортировка

### Steps To Reproduce

Добавить в ресурс метод
```
public function query(): Builder
{
    return parent::resolveItemQuery();
}
```

Попытаться отсортировать по полю у которого указан _sortable()_

**Comment by lee-to** [comment]
У тебя тут ошибка ты используешь билдер по карточке который включается при обращении к записи а нужно parent::query()

**Comment by AkostDev** [comment]
О точно, прошу прощения
