### ISSUE TITLE
Поля отношений не работают в декорациях

### ISSUE THREAD

**Issue by gsdevx** [moonshine-software/moonshine#703]
### MoonShine Version

2.4.2

### Laravel Version

10.35.0

### PHP Version

8.2

### Description

В ресурсах поля отношений игнорируют декорации

### Steps To Reproduce

Сделать Tabs,  поместить внутрь Tab'ы а внутр попробовать вставить поля например HasOne/HasMany

**Comment by DissNik** [comment]
Данные поля отображаются всегда вне формы, если же вы хотите их отобразить внутри формы, то воспользуйтесь полем [Json в режиме отношений](https://moonshine-laravel.com/docs/section/fields-json#relation) или можно реализовать как в этой [статье](https://cutcode.dev/articles/kastomizaciia-stranicy-formy-moonshine-20)
