### ISSUE TITLE
BelongsTo - 403 у ресурса

### ISSUE THREAD

**Issue by AkostDev** [moonshine-software/moonshine#704]
### MoonShine Version

2.4.2

### Laravel Version

10.34.2

### PHP Version

8.2

### Description

Если у ресурса метод _getActiveActions_ возвращает пустой массив, то у поля BelongsTo к этому ресурсу при переходе открывается 403 ошибка

### Steps To Reproduce

Задать ресурсу метод
```
public function getActiveActions(): array
    {
        return [];
    }
```
В другом ресурсе через BelogsTo указать первый ресурс

**Comment by lee-to** [comment]
В таком случае стоит у поля сделать свой link() или указать его пустым

**Comment by lee-to** [comment]
Можно конечно и в коде сделать бед линка, надо подумать, тут скорее discussion а не issue

**Comment by AkostDev** [comment]
> Можно конечно и в коде сделать бед линка, надо подумать, тут скорее discussion а не issue

Как вариант, можно сделать просто текст вместо ссылки - да
