### ISSUE TITLE
search not work for outside fields on Detail Page

### ISSUE THREAD

**Issue by k-rustemuly** [moonshine-software/moonshine#720]
### MoonShine Version

2.4

### Laravel Version

10.10

### PHP Version

8.1

### Description

Поиск по HasMany field в детальном просмотре ресурса не работает

### Steps To Reproduce

в ресурсе: 
```php
public function fields(): array
{
    return [
        ID::make()
            ->useOnImport()
            ->showOnExport()
            ->sortable(),

        HasMany::make('Comments', resource: new CommentResource())
            ->async()
            ->creatable()
            ->hideOnIndex(),
    ];
}
```
При просмотре одной записи этого ресурса поиск по Comments не будет работать

**Comment by k-rustemuly** [comment]
@lee-to  пагинация тоже будет работать?

**Comment by lee-to** [comment]
> @lee-to пагинация тоже будет работать?

должна, поле будет находить, до этого просто поле не находило
