### ISSUE TITLE
Undefined variable $data component/menu/index.blade 

### ISSUE THREAD

**Issue by abdullajon8111** [moonshine-software/moonshine#734]
### MoonShine Version

2.4.3

### Laravel Version

10.38.1

### PHP Version

8.1

### Database Driver & Version

mysql 8.0

### Description

composer update moonshine version 2.4.3 and 500 error Undefined variable $data

### Steps To Reproduce

composer update moonshine version 2.4.3 and 500 error Undefined variable $data
![Uploading Screenshot_2.png…]()

**Comment by lee-to** [comment]
Сбросьте кеш
