### ISSUE TITLE
Не работает default в ресурсах

### ISSUE THREAD

**Issue by projct1** [moonshine-software/moonshine#738]
### MoonShine Version

2.5

### Laravel Version

10.38.2

### PHP Version

8.3

### Database Driver & Version

MySQL 8

### Description

Настроил ресурс так:
```php
class CategoryResource extends TreeResource
{
    //...

    public function fields(): array
    {
        return [
            Block::make([
                ID::make()->sortable(),
                //...
                BelongsTo::make('Сущность', 'taxonomy', resource: new TaxonomyResource)
                    ->default(1) // строкой тоже не работает
                    ->hideOnForm()
            ])
        ];
    }

    public function rules(Model $item): array
    {
        return [
            'name' => 'required'
        ];
    }
}
```
При попытке добавить сущность `CategoryResource` вылазит ошибка:
`SQLSTATE[HY000]: General error: 1364 Field 'taxonomy_id' doesn't have a default value`
То есть единичка не подставилась.

### Steps To Reproduce

- Создать ресурс
- Добавить поле в метод `fields`, указав метод `default`
- Попытаться добавить сущность

**Comment by DissNik** [comment]
Поле BelongsTo является полем отношения и метод ```default()``` ожидает объект модели
```php
BelongsTo::make('Сущность', 'taxonomy', resource: new TaxonomyResource())
   ->default(Taxonomy::find(1))
```

https://moonshine-laravel.com/docs/resource/fields/fields-belongs_to#default

Метод ```hideOnForm()``` исключит данное поле из формы, таким образом вы вообще не передаете значение при сохранении

**Comment by projct1** [comment]
> Поле BelongsTo является полем отношения и метод `default()` ожидает объект модели
> 
> ```
> BelongsTo::make('Сущность', 'taxonomy', resource: new TaxonomyResource())
>    ->default(Taxonomy::find(1))
> ```
> 
> https://moonshine-laravel.com/docs/resource/fields/fields-belongs_to#default
> 
> Метод `hideOnForm()` исключит данное поле из формы, таким образом вы вообще не передаете значение при сохранении

Пробовал модель передавать, всё равно не работает.

А `hideOnForm` специально делаю для того, чтобы не было в форме с реквестом и срабатывал `default`.

**Comment by projct1** [comment]
> Поле BelongsTo является полем отношения и метод `default()` ожидает объект модели

Тогда почему у в тайпхинте указано `mixed`, раз строго объект модели надо передавать?
