### ISSUE TITLE
Не работает для Laravel Octane (Swool)

### ISSUE THREAD

**Issue by PoretskovOleg** [moonshine-software/moonshine#739]
### MoonShine Version

2.5

### Laravel Version

10.38.8

### PHP Version

8.1.7

### Description

Для Laravel Octane первый раз страница отображается, на второй-третий раз появляется ошибка. При выполнении комнады `php artisan clear-compiled` страница снова доступна на 1-2 захода, затем опять ошибка:

>  Call to a member function route() on null

> vendor/moonshine/moonshine/src/MoonShineRouter.php:117

### Steps To Reproduce

1. Установить Laravel,
2. Установить Laravel Octane (Swool)
3. Устновить Moonshine
4. Зайти в аминку и 2-3 раза перезагрузить страницу

**Comment by lee-to** [comment]
Issue оставим, но мы пока не завершили интеграцию с Octane, после праздников продолжим и сообщим в релизе
