### ISSUE TITLE
Поле BelongsToMany и required работают неверно

### ISSUE THREAD

**Issue by projct1** [moonshine-software/moonshine#741]
### MoonShine Version

2.5

### Laravel Version

10

### PHP Version

8.3

### Database Driver & Version

MySQL 8

### Description

Если у поля `BelongsToMany` поставить `->required()`, то нужно отметить обязательно все галки.
Понятно, что проставляется атрибут `required` у всех чекбоксов и так работает html. Но у нас же муншайн, где всё продумано :)

### Steps To Reproduce

1) Создать любой ресурс
2) Добавить поле `BelongsToMany` с вызовом `->required()`
3) Выбрать только одну галку из многих
4) Попробовать сохранить (не получится, так как надо выбрать все галки)

**Comment by lee-to** [comment]
Required добавляет html атрибут required, никакой доп логики не несет, если вам нужно настраивать валидацию то используйте rules, либо пишите свой js c тем как вы видите валидацию на фронте
