### ISSUE TITLE
Генерация слага для других локалей

### ISSUE THREAD

**Issue by projct1** [moonshine-software/moonshine#743]
### MoonShine Version

2.5

### Laravel Version

10

### PHP Version

8.3

### Database Driver & Version

MySQL 8

### Description

Сейчас в поле `Slug` нельзя задать локаль, в отличае от `separator`. Поэтому, все слаги генерируются на основе дефолтной локали `en`, вот оригинал функции:
```php
public function slug($separator = '-', $language = 'en', $dictionary = ['@' => 'at'])
{
    return new static(Str::slug($this->value, $separator, $language, $dictionary));
}
```
Было бы здорово добавить ещё один параметр в поле `Slug` для локали. А ещё лучше, если бы муншайн генерировал слаг на основе локали из основного конфига приложения `config/app.php`.

**Comment by khlystou** [comment]
Да, предлогаю добавить метод ```Slug::make()->locale(string $locale)```, а по умолчанию использовать локаль приложения из ```config('app.locale')```
