### ISSUE TITLE
bulk error

### ISSUE THREAD

**Issue by k-rustemuly** [moonshine-software/moonshine#744]
### MoonShine Version

2.5.1

### Laravel Version

10.10

### PHP Version

8.1

### Description

```php
ActionButton::make('Button 1', '/')
    ->bulk(),
```
После обновление страницы пропадает кнопка bulk
![изображение](https://github.com/moonshine-software/moonshine/assets/16911003/956a2f13-b6fd-4061-a41e-7467f56075c3)
Только после выбора другого item или снятие появляется
![изображение](https://github.com/moonshine-software/moonshine/assets/16911003/788ac04a-e17c-4678-816f-dd66503db3b5)

### Steps To Reproduce

ActionButton::make('Button 1', '/')
    ->bulk(),

**Comment by lee-to** [comment]
Обновления страницы имеется ввиду async reload?
