### ISSUE TITLE
Поле select сохраняется, но не выводится сохранённое значение

### ISSUE THREAD

**Issue by projct1** [moonshine-software/moonshine#745]
### MoonShine Version

2.5

### Laravel Version

10

### PHP Version

8.3

### Database Driver & Version

MySQL 8.0

### Description

В ресурсе передаю обычный массив в качестве опций:
```php
public function fields(): array
{
    $statuses = [
        "draft" => "Черновик",
        "inactive" => "Неактивный",
        "active" => "Активный",
        "unavailable" => "Выключенный",
        "retired" => "Архивный",
    ];

    return [
        Select::make('Статус', 'state')->options($statuses),
    ];
}
```
При сохранении поле в базе обновляется, но при заходе в карточку отображается пустота:
![image](https://github.com/moonshine-software/moonshine/assets/9752959/b4645569-11da-4f14-84cf-c5a4048b3bc6)

**Comment by DissNik** [comment]
Воспроизвести ошибку не удалось, возможно вы переопределили поля для детальной страницы и не передали там  options

**Comment by projct1** [comment]
> Воспроизвести ошибку не удалось, возможно вы переопределили поля для детальной страницы и не передали там options

В том-то и прикол, что у меня голый ресурс, ничего нигде не переопределяю:
![image](https://github.com/moonshine-software/moonshine/assets/9752959/650e76d2-1ced-40ff-9e44-0a715f31cc95)
А выводится всегда первый элемент из списка:
![image](https://github.com/moonshine-software/moonshine/assets/9752959/48eec372-979c-44ec-81a4-53fef10e82e0)
Хотя в базе значение другое. Ну и сохраняется в базу выбранное значение.

**Comment by lee-to** [comment]
Вы в примере показываете просто массив, теперь уже Enum, может у вас и каст какой то у модели есть который вы нам не показываете? От таких issue очень мало толку

**Comment by DissNik** [comment]
Предоставьте больше данных, миграцию, модель, ресурс, чтобы можно было точно восстановить вашу ситуацию

**Comment by lee-to** [comment]
> Предоставьте больше данных, миграцию, модель, ресурс, чтобы можно было точно восстановить вашу ситуацию

Ставлю на то что есть cast на поле state и скорее всего там не строка)

**Comment by projct1** [comment]
> Вы в примере показываете просто массив, теперь уже Enum, может у вас и каст какой то у модели есть который вы нам не показываете? От таких issue очень мало толку

В массиве это:
```php
    $statuses = [
        "draft" => "Черновик",
        "inactive" => "Неактивный",
        "active" => "Активный",
        "unavailable" => "Выключенный",
        "retired" => "Архивный",
    ];
```

**Comment by projct1** [comment]
Вот, записал видео для наглядности: https://skr.sh/vNVyMoFjPXN

**Comment by projct1** [comment]
> Ставлю на то что есть cast на поле state и скорее всего там не строка)

Да, так и есть, что-то я затупил совсем. Сорри за беспокойство)
