### ISSUE TITLE
Не заполняются pivot-поля в BelongsToMany

### ISSUE THREAD

**Issue by projct1** [moonshine-software/moonshine#753]
### MoonShine Version

2.5.2

### Laravel Version

10

### PHP Version

8.3

### Description

```php
BelongsToMany::make('Поставщики', 'suppliers', resource: new SupplierResource)
    ->columnLabel('Поставщик')
    ->inLine(', ')
    ->hideOnIndex()
    ->fields([
        Number::make('Цена', 'price')->required(),
        Number::make('Дилерская цена', 'price_dealer')->required(),
        Text::make('Артикул', 'sku')->required(),
        Switcher::make('Активно', 'active')
    ])
```
При создании ресурса `ProductResource` пивотные поля (`price`, `price_dealer` etc) сохраняются в базе, но при редактировании эти поля пустые:
![image](https://github.com/moonshine-software/moonshine/assets/9752959/5a705c63-c24d-4076-b41a-1d18f3a52ae6)

**Comment by lee-to** [comment]
В отношении в моделе нужно указывать withPivot
Рекомендую вам изучить Laravel прежде чем пользоваться MoonShine

**Comment by lee-to** [comment]
Последующие твои issue я буду закрывать без комментариев
