### ISSUE TITLE
Баг в ActionButton

### ISSUE THREAD

**Issue by khlystou** [moonshine-software/moonshine#765]
### MoonShine Version

2.6.2

### Laravel Version

10.40.0

### PHP Version

8.1.5

### Description

ActionButton в async-режиме отрабатывает раньше, чем withConfirm

### Steps To Reproduce

```
ActionButton::make(...)->async(...)->withConfirm(...)
```

**Comment by lee-to** [comment]
А зачем ей async если модалку открывает? У нее получается async на клик вешается
Если нужен контент в модалке асинк тогда уже в контенте указать или на метод withConfirm

А сейчас получается можно на клик повесить что нибудь с запросом и внутри модалки

**Comment by khlystou** [comment]
Ну смотри, простой пример: Удаление данных, которые были помечены как удалённые,и теперь их нужно удалить навсегда. При клике на унопку, нужно запросить подтверждение, но при этом сам запрос сделать асинхронным и обновить табличку после успеха.

**Comment by lee-to** [comment]
> Ну смотри, простой пример: Удаление данных, которые были помечены как удалённые,и теперь их нужно удалить навсегда. При клике на унопку, нужно запросить подтверждение, но при этом сам запрос сделать асинхронным и обновить табличку после успеха.

Ну получается что просто кнопка с модалкой а уже модалка имеет флаг асинк чтобы получить контент а форма внутри которая удаляет тоже асинк и с событием обновления таблицы

**Comment by lee-to** [comment]
К примеру кнопка удаления которая в коробке, она сама без async а вот форма внутри async

**Comment by lee-to** [comment]
Если бы контент модалки должен был бы быть асинком то флаг вешается на модалку
