### ISSUE TITLE
В BelongsToMany метод asyncSearch работает неверно

### ISSUE THREAD

**Issue by Sckatik** [moonshine-software/moonshine#769]
### MoonShine Version

2.6.6

### Laravel Version

10.4.0

### PHP Version

8.2.2

### Database Driver & Version

Mysql 8.1.0

### Description

В FilmResource такой код:
```
   Fragment::make([
              BelongsToMany::make('Актеры', 'actors', resource: new ActorResource())
                                ->fields([
                                    Text::make('Название роли', 'role_name'),
                                ])->withImage('image', 'public', 'actors')
                                ->asyncSearch()->creatable()->hideOnIndex()
                ])->name('actors')->updateAsync([
                            'resourceItem'=>$this->getItemID()
                ]),
```

В версии Moonshine 2.4.3 данный код работал корректно. 
В текущей версии Moonshine не прикрепляется запись. Подставляется неверный id. Прикрепляю скриншот. Есть подозрение что один и тот же всегда. Какую бы запись я бы не выбрал. Убирал Fragment, ошибка все равно такая же.
В ActorResource установлены:
 ```
   protected bool $isAsync = true;

    protected bool $createInModal = true;
```
Связь в модели Actor - установлена такая -      
`  public function films(): BelongsToMany
    {
        return $this->belongsToMany(Film::class)->withPivot('role_name')->withTimestamps();
    }
`

В модели Film -     
```
public function actors(): BelongsToMany
    {
        return $this->belongsToMany(Actor::class)->withPivot('role_name')->withTimestamps();
    }
```

### Steps To Reproduce

![Screenshot at Jan 14 19-39-53](https://github.com/moonshine-software/moonshine/assets/5471061/cf20b18f-a081-44df-8344-dfbc1c0934d7)

**Comment by lee-to** [comment]
Спасибо за найденный баг, исправлено в релизе 2.6.7
