### ISSUE TITLE
flash

### ISSUE THREAD

**Issue by sashagm** [moonshine-software/moonshine#778]
### MoonShine Version

2.x

### Laravel Version

10.38

### PHP Version

8.2

### Description

Trying to access array offset on value of type bool {"view":{"view":"/home/h/s/vendor/moonshine/moonshine/resources/views/components/layout/flash.blade.php","data":{"errors":"<pre class=sf-dump id=sf-dump-194011606 data-indent-pad=\"  \"><span class=sf-dump-note>Illuminate\\Support\\ViewErrorBag</span> {<a class=sf-dump-ref>#921</a><samp data-depth=1 class=sf-dump-expanded>
  #<span class=sf-dump-protected title=\"Protected property\">bags</span>: []
</samp>}
</pre><script>Sfdump(\"sf-dump-194011606\", {\"maxDepth\":3,\"maxStringLength\":160})</script>
","key":"<pre class=sf-dump id=sf-dump-389518381 data-indent-pad=\"  \">\"<span class=sf-dump-str title=\"5 characters\">alert</span>\"
</pre><script>Sfdump(\"sf-dump-389518381\", {\"maxDepth\":3,\"maxStringLength\":160})</script>
","type":"<pre class=sf-dump id=sf-dump-815088161 data-indent-pad=\"  \">\"<span class=sf-dump-str title=\"4 characters\">info</span>\"
</pre><script>Sfdump(\"sf-dump-815088161\", {\"maxDepth\":3,\"maxStringLength\":160})</script>
","withToast":"<pre class=sf-dump id=sf-dump-1974224903 data-indent-pad=\"  \"><span class=sf-dump-const>true</span>
</pre><script>Sfdump(\"sf-dump-1974224903\", {\"maxDepth\":3,\"maxStringLength\":160})</script>
","removable":"<pre class=sf-dump id=sf-dump-1659620136 data-indent-pad=\"  \"><span class=sf-dump-const>true</span>
</pre><script>Sfdump(\"sf-dump-1659620136\", {\"maxDepth\":3,\"maxStringLength\":160})</script>
","componentName":"<pre class=sf-dump id=sf-dump-1344834159 data-indent-pad=\"  \"><span class=sf-dump-const>null</span>
</pre><script>Sfdump(\"sf-dump-1344834159\", {\"maxDepth\":3,\"maxStringLength\":160})</script>
","attributes":"<pre class=sf-dump id=sf-dump-212305383 data-indent-pad=\"  \"><span class=sf-dump-note>Illuminate\\View\\ComponentAttributeBag</span> {<a class=sf-dump-ref>#1998</a><samp data-depth=1 class=sf-dump-expanded>
  #<span class=sf-dump-protected title=\"Protected property\">attributes</span>: []
</samp>}
</pre><script>Sfdump(\"sf-dump-212305383\", {\"maxDepth\":3,\"maxStringLength\":160})</script>
","name":"<pre class=sf-dump id=sf-dump-2003221561 data-indent-pad=\"  \"><span class=sf-dump-const>null</span>
</pre><script>Sfdump(\"sf-dump-2003221561\", {\"maxDepth\":3,\"maxStringLength\":160})</script>
"}},"userId":1,"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): Trying to access array offset on value of type bool at /home/h/s/vendor/moonshine/moonshine/resources/views/components/layout/flash.blade.php:14)
[stacktrace]

### Steps To Reproduce

плавающая ошибка, лечится сбросом кеша и куки страницы, нужна войти в админку

**Comment by lee-to** [comment]
Мало данных и больше похоже что это вы где то допускаете ошибку и передаете не правильно данные в toast
