### ISSUE TITLE
Конфликт таблиц уведомлений

### ISSUE THREAD

**Issue by pepperfm** [moonshine-software/moonshine#791]
### MoonShine Version

2.7

### Laravel Version

10.40.0

### PHP Version

8.2.15

### Database Driver & Version

image: 'postgres:15'

### Description

Если существует таблица `notifications`, то при установке пакета нет конфликтов и ошибок. Этот момент просто скипается и после логина получается SQLSTATE error

ps. хочу поставить себя в Assignees. пока не пойму как (создаю тикет тут лишь как запоминалку себе)

### Steps To Reproduce

`php artisan make:migration "create notifications table"`
`php artisan migrate`
`php artisan moonshine:install`

**Comment by lee-to** [comment]
Смотри на самом деле в муншайн проверка если таблица есть то не добавляет а ты создаешь миграцию которая запускается после муншайн и проверку не делаешь, то есть тут разработчик совершает ошибку зная что работает с муншайн, но возможно я не прав

**Comment by pepperfm** [comment]
Если я правильно понял, то у меня обратная ситуация:

- уже существующий проект
- уже существующая таблица
- и только потом установка муншайн с самого чистого листа -- composer require
