### ISSUE TITLE
Unique validation не отрабатывает

### ISSUE THREAD

**Issue by IgorPetrovPRO** [moonshine-software/moonshine#799]
### MoonShine Version

2.7.2

### Laravel Version

10.43

### PHP Version

8.2

### Database Driver & Version

MySQL 8

### Description

Не удается осуществить валидацию и проверить на уникальность. Всегда сохраняет в итоге, даже если дубли уже есть.

### Steps To Reproduce

Создать любую модель, в которую добавить поле типа string и в БД сделать его уникальным.

Далее создается ресурс через extends ModelResource и прописывать там следующие правила

```
 public function prepareForValidation(): void
    {
        request()?->merge([
            'phone' => request()
                ?->string('phone')
                ->replace('(', '')
                ->replace(')', '')
                ->replace('+', '')
                ->replace(' ', '')
                ->replace('-', '')
                ->value()
        ]);
    }

  public function rules(Model $item): array
  {

      return [
           'phone' =>['required', Rule::unique('workers','phone')->ignoreModel($item)],
      ];
  }
```

**Comment by k-rustemuly** [comment]
попробуй через exists

**Comment by lee-to** [comment]
```php
public function prepareForValidation(): void
    {
        request()?->merge([
            'phone' => request()
                ?->string('phone')
                ->replace('(', '')
                ->replace(')', '')
                ->replace('+', '')
                ->replace(' ', '')
                ->replace('-', '')
                ->value()
        ]);
    }
```

Так работать не будет и у вас будет запрос с тем же самым телефоном который был в инпуте
Нужно использовать 

```php
public function prepareForValidation(): void
    {
        $this->merge([
            'phone' => ...
        ]);
    }
```

Вы должны понимать что сам муншайн никакого отношения к валидации не имеет, валидация полностью на стороне ларавел, пример что я дал он из документации

**Comment by lee-to** [comment]
Уже написал и потом понял что мы ведь в ресурсе

**Comment by lee-to** [comment]
Так я сделаю фикс но вам надо будет заменить request() на moonShineRequest(), можете сразу это сделать и ждать релиз

**Comment by IgorPetrovPRO** [comment]
Спасибо
