### ISSUE TITLE
error async message type key

### ISSUE THREAD

**Issue by k-rustemuly** [moonshine-software/moonshine#807]
### MoonShine Version

2.5

### Laravel Version

10.10

### PHP Version

8.1

### Description

Ошибка в [документации ](https://moonshine-laravel.com/docs/resource/actionbutton/action_button?change-moonshine-locale=ru#async)или в [коде](https://github.com/moonshine-software/moonshine/blob/bbcad10622f2150fa6f6a19fbf2072b728cf50cd/resources/js/alpine/asyncFunctions.js#L64C25-L64C37)

### Steps To Reproduce

ответ от async в виде
```
{
    message: 'Toast', 
    type: 'error', 
    redirect: '/url'
}
```
игнорируется 'type'

**Comment by lee-to** [comment]
Ошибка в документации, правильно messageType
