### ISSUE TITLE
Проблема с selectMode в BelongsToMany

### ISSUE THREAD

**Issue by AJIUK** [moonshine-software/moonshine#809]
### MoonShine Version

2.7.2

### Laravel Version

10.43.0

### PHP Version

8.3.2-1

### Database Driver & Version

MySQL 8.0.32

### Description

При использовании метода selectMode в BelongsToMany возникает ошибка в js, из-за которой не отрисовывается страница редактирования.

![image](https://github.com/moonshine-software/moonshine/assets/11522300/1a4386ab-b119-40ea-b6f1-adf4f712bead)

Если вместе с selectMode использовать asyncSearch, то ошибки при создании или редактировании нет, пока нет связанных элементов. После привязки - ошибка повторяется.

### Steps To Reproduce

Есть отношение BelongsToMany между моделями Category и Attribute, в обычном режиме все работает, при selectMode что-то ломается на фронте.

Обычный режим:
![image](https://github.com/moonshine-software/moonshine/assets/11522300/f35c926a-e343-46f6-aa29-b1cb1e7f8570)
![image](https://github.com/moonshine-software/moonshine/assets/11522300/c7c9773f-9268-4ac7-985b-d50f373d984c)

Режим списка, ошибка в любом случае:
![image](https://github.com/moonshine-software/moonshine/assets/11522300/737ec668-a6f5-4f9c-9219-4ec3174f1b9c)
![image](https://github.com/moonshine-software/moonshine/assets/11522300/a2fb4868-369d-4098-a242-dfa15e0bad74)

Режим списка + асинхронный поиск, ошибки нету при создании или редактировании модели без связей:
![image](https://github.com/moonshine-software/moonshine/assets/11522300/94533d6f-59e2-4f89-a023-7f7cc23f2ffd)
До сохранения:
![image](https://github.com/moonshine-software/moonshine/assets/11522300/c8fa9d34-001e-4872-a6e4-3ef2e68e2c1d)
После сохранения:
![image](https://github.com/moonshine-software/moonshine/assets/11522300/a2fb4868-369d-4098-a242-dfa15e0bad74)
При этом он сохраняет связь, что видно в обычном режиме и бд:
![image](https://github.com/moonshine-software/moonshine/assets/11522300/c32c0e93-0aba-4d6b-aaec-1846d8323d27)

**Comment by lee-to** [comment]
Спасибо за issue! Я проверил у себя и не обнаружил никаких ошибок, думаю дело в чем то еще, пришлите ресурс полностью

**Comment by AJIUK** [comment]
CategoryResource:
```
<?php

declare(strict_types=1);

namespace App\MoonShine\Resources;

use Illuminate\Database\Eloquent\Model;
use App\Models\Category;

use MoonShine\Resources\ModelResource;
use MoonShine\Fields\ID;
use MoonShine\Fields\Relationships\BelongsTo;
use MoonShine\Fields\Relationships\BelongsToMany;
use MoonShine\Fields\Select;
use MoonShine\Fields\Slug;
use MoonShine\Fields\Text;

/**
 * @extends ModelResource<Category>
 */
class CategoryResource extends ModelResource
{
    protected string $model = Category::class;

    protected string $title = 'Категории';

    public string $column = 'name';

    public function indexFields(): array
    {
        return [
            ID::make()->sortable(),

            Select::make('Статус', 'status')
            ->options(Category::$statuses)
            ->default('new'),

            Text::make('Название', 'name'),
            Slug::make('Код', 'slug'),

            BelongsTo::make('Родитель', 'parent', resource: new CategoryResource())
            ->nullable(),
        ];
    }

    public function formFields(): array
    {
        return [
            ID::make()->sortable(),

            Select::make('Статус', 'status')
            ->options(Category::$statuses)
            ->default('new'),

            Text::make('Название', 'name'),
            Slug::make('Код', 'slug')->from('name'),

            BelongsTo::make('Родитель', 'parent', resource: new CategoryResource())
            ->nullable(),

            BelongsToMany::make('Атрибуты', 'attributes', resource: new AttributeResource())
            // ->asyncSearch()
            // ->selectMode(),
        ];
    }

    public function detailFields(): array
    {
        return [
            ID::make()->sortable(),

            Select::make('Статус', 'status')
            ->options(Category::$statuses)
            ->default('new'),

            Text::make('Название', 'name'),
            Slug::make('Код', 'slug'),

            BelongsTo::make('Родитель', 'parent', resource: new CategoryResource())
            ->nullable(),

            BelongsToMany::make('Атрибуты', 'attributes', resource: new AttributeResource()),
        ];
    }

    public function rules(Model $item): array
    {
        return [];
    }
}
```

AttributeResource:
```
<?php

declare(strict_types=1);

namespace App\MoonShine\Resources;

use Illuminate\Database\Eloquent\Model;
use App\Models\Attribute;

use MoonShine\Resources\ModelResource;
use MoonShine\Fields\ID;
use MoonShine\Fields\Select;
use MoonShine\Fields\Text;

/**
 * @extends ModelResource<Attribute>
 */
class AttributeResource extends ModelResource
{
    protected string $model = Attribute::class;

    protected string $title = 'Атрибуты';

    public string $column = 'name';

    public function indexFields(): array
    {
        return [
            ID::make()->sortable(),

            Text::make('Название', 'name'),
            Text::make('Код', 'code'),

            Select::make('Тип', 'type')
            ->options(Attribute::$types)
            ->default('text'),
        ];
    }

    public function formFields(): array
    {
        return [
            ID::make()->sortable(),

            Text::make('Название', 'name'),
            Text::make('Код', 'code'),

            Select::make('Тип', 'type')
            ->options(Attribute::$types)
            ->default('text'),
        ];
    }

    public function detailFields(): array
    {
        return [
            ID::make()->sortable(),

            Text::make('Название', 'name'),
            Text::make('Код', 'code'),

            Select::make('Тип', 'type')
            ->options(Attribute::$types)
            ->default('text'),
        ];
    }

    public function rules(Model $item): array
    {
        return [];
    }
}
```

**Comment by lee-to** [comment]
Покажите пожалуйста как выглядит html тег select, скопируйте именно код селекта а не врапперов и у основной формы будут дата атрибуты x-init вот его тоже покажите

**Comment by AJIUK** [comment]
```
<select class="form-select" x-data="select('')" data-search-enabled="data-search-enabled" data-remove-item-button="data-remove-item-button" value="[1]" id="attributes" name="attributes[]" multiple="multiple" x-on:change="onChangeField($event)">
```
![image](https://github.com/moonshine-software/moonshine/assets/11522300/cfbd594b-a1cb-4668-81f8-a992c545b455)

```
<form class="form" method="POST" x-data="formBuilder(`crud`, [])" x-init="init({&quot;whenFields&quot;:[],&quot;reactiveUrl&quot;:&quot;&quot;})" action="http://127.0.0.1/admin/resource/category-resource/crud/1" enctype="multipart/form-data" x-id="['form']" :id="$id('form')">
```
![image](https://github.com/moonshine-software/moonshine/assets/11522300/8bb090aa-6bbb-4406-9fe4-a1bdbf154381)

**Comment by DissNik** [comment]
Попробуйте переименовать связь `attributes` например на `categoryAttributes`

**Comment by AJIUK** [comment]
Это сработало
