### ISSUE TITLE
Всегда подгружать контент в модальном окне

### ISSUE THREAD

**Issue by alglyzin** [moonshine-software/moonshine#811]
### MoonShine Version

2.7.3

### Laravel Version

10

### PHP Version

8.1

### Description

Контент в модальном окне загружается асинхронно только раз, при повторном открытии отображается старое содержимое (то есть повторной погрузки не осуществляется). Необходимо добавить метод, который бы указывал Moonshine повторно делать ajax запрос. Это полезно например для функции предпросмотра, когда содержимое должно сгенерироваться на лету каждый раз без перезагрузки страницы.

### Steps To Reproduce

```php
public function buttons(): array
{
    return [
        ActionButton::make('Просмотр', url: route('document.view'))
            ->inModal(
            'Предварительный просмотр',
            async: true,
            auto: true,
            closeOutside: true
        )->primary()->icon('heroicons.eye'),
    ];
}
```

**Comment by lee-to** [comment]
```php
public function buttons(): array
{
    return [
        ActionButton::make('Просмотр', url: route('document.view'))
            ->inModal(
            'Предварительный просмотр',
            async: true,
            auto: true,
            closeOutside: true,
            attributes: ['data-always-load' => true]
        )->primary()->icon('heroicons.eye'),
    ];
}
```
