### ISSUE TITLE
Проблема с полем BelongToMany

### ISSUE THREAD

**Issue by AkostDev** [moonshine-software/moonshine#843]
### MoonShine Version

2.8.1

### Laravel Version

10.47

### PHP Version

8.2

### Database Driver & Version

MariaDB 10

### Description

При сохранении поля BelongsToMany выпала ошибка: `Вложенные массивы не могут быть переданы методу WhereIn.`

![image](https://github.com/moonshine-software/moonshine/assets/11013417/c62a29af-8f2d-4eec-a4df-75b024121a6f)

### Steps To Reproduce

Тут сложно сказать, но попробую:
Есть модель `User` и модель `Contract`. В каждой из них есть связь `BelongsToMany` через _pivot_ таблицу `ContractUser`.
```
// User
public function contracts(): BelongsToMany
    {
        return $this->belongsToMany(Contract::class)
            ->using(ContractUser::class);
    }

// Contract
public function users(): BelongsToMany
    {
        return $this->belongsToMany(User::class)
            ->using(ContractUser::class);
    }
```

Для каждой модели есть ресурс с полем BelongsToMany
```
// UserResource
BelongsToMany::make('Contracts', 'contracts', resource: new ContractResource())
    ->selectMode()

// ContractResource
BelongsToMany::make('Users', 'users', resource: new UserResource())
    ->selectMode()
```

При сохранении из ContractResource проблем нет, а вот из UserResource - выдает ошибку.

**Comment by AkostDev** [comment]
Поковырявшись в коде, понял, что упустил немаловажный нюанс. У модели `User` установлено свойство:
`protected $with = ['contracts'];`.

В таком случае в методе `prepareFill` класса поля `BelongsToMany`, при условии, что стоит у поля `->selectMode()`:
```
$keys = $this->isSelectMode()
    ? $values
    : array_keys($values);

$related = $this->getRelation()?->getRelated();

$casted->setRelation(
    $this->getRelationName(),
    $related?->query()
        ->whereIn($related->getKeyName(), $keys)?->get() ?? []
);
```

переменная `$keys` содержит не одномерный массив (допустим айдишников), а массив отношения `contracts`:

![image](https://github.com/moonshine-software/moonshine/assets/11013417/274e6ff6-7a46-4039-8486-f3291ef692b1)

Немного изменив код метода `prepareFill` всё заработало:

```
$related = $this->getRelation()?->getRelated();

$keys = $this->isSelectMode()
    ? collect($values)->pluck($related->getKeyName())->toArray() // вот тут
    : array_keys($values);

$casted->setRelation(
    $this->getRelationName(),
    $related?->query()
        ->whereIn($related->getKeyName(), $keys)?->get() ?? []
);
```

@lee-to насколько адекватное решение?

**Comment by lee-to** [comment]
> Поковырявшись в коде, понял, что упустил немаловажный нюанс. У модели `User` установлено свойство: `protected $with = ['contracts'];`.
> 
> В таком случае в методе `prepareFill` класса поля `BelongsToMany`, при условии, что стоит у поля `->selectMode()`:
> 
> ```
> $keys = $this->isSelectMode()
>     ? $values
>     : array_keys($values);
> 
> $related = $this->getRelation()?->getRelated();
> 
> $casted->setRelation(
>     $this->getRelationName(),
>     $related?->query()
>         ->whereIn($related->getKeyName(), $keys)?->get() ?? []
> );
> ```
> 
> переменная `$keys` содержит не одномерный массив (допустим айдишников), а массив отношения `contracts`:
> 
> ![image](https://private-user-images.githubusercontent.com/11013417/310602081-274e6ff6-7a46-4039-8486-f3291ef692b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjI4MTQsIm5iZiI6MTcwOTgyMjUxNCwicGF0aCI6Ii8xMTAxMzQxNy8zMTA2MDIwODEtMjc0ZTZmZjYtN2E0Ni00MDM5LTg0ODYtZjMyOTFlZjY5MmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE0NDE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MWQzOTgxNzY4NzY3MzViNzQyMjkwZWQ3M2ZkZGQzN2IyZmY0NTA5ZDg0ODIzNjhlZTJjNTIzMTEzMGJiNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EqPTNKPNhqclnNWJCYwfJnirGQaPdF6LYBIf5yxYluo)
> 
> Немного изменив код метода `prepareFill` всё заработало:
> 
> ```
> $related = $this->getRelation()?->getRelated();
> 
> $keys = $this->isSelectMode()
>     ? collect($values)->pluck($related->getKeyName())->toArray() // вот тут
>     : array_keys($values);
> 
> $casted->setRelation(
>     $this->getRelationName(),
>     $related?->query()
>         ->whereIn($related->getKeyName(), $keys)?->get() ?? []
> );
> ```
> 
> @lee-to насколько адекватное решение?

Тогда сломаются фильтры, тут проблема в том что мы в эту if конструкцию вообще не должны попадать

**Comment by AkostDev** [comment]
> Тогда сломаются фильтры, тут проблема в том что мы в эту if конструкцию вообще не должны попадать

И как быть тогда? Когда-нибудь, не только я попаду в эту if конструкцию)

**Comment by lee-to** [comment]
> > Тогда сломаются фильтры, тут проблема в том что мы в эту if конструкцию вообще не должны попадать
> 
> И как быть тогда? Когда-нибудь, не только я попаду в эту if конструкцию)

Буду фиксить! Я просто к тому что твое решение не подойдет

**Comment by lee-to** [comment]
Попробуй у себя вот такое решение
```php
protected function prepareFill(array $raw = [], mixed $casted = null): mixed
{
    $values = parent::prepareFill($raw, $casted);

    if (blank($values) && filled($raw)) {
        $values = parent::prepareFill($raw);
    }

    if ($this->isAsyncSearch()) {
        $this->memoizeValues = $values;
        $this->memoizeAllValues = $values;
    }

    return $values;
}
```

**Comment by AkostDev** [comment]
> Попробуй у себя вот такое решение
> 
> ```
> protected function prepareFill(array $raw = [], mixed $casted = null): mixed
> {
>     $values = parent::prepareFill($raw, $casted);
> 
>     if (blank($values) && filled($raw)) {
>         $values = parent::prepareFill($raw);
>     }
> 
>     if ($this->isAsyncSearch()) {
>         $this->memoizeValues = $values;
>         $this->memoizeAllValues = $values;
>     }
> 
>     return $values;
> }
> ```

Решение помогло сохранить данные, но вылезла другая ошибка (метод `resolvePreview` класса `BelongsToMany`):

![image](https://github.com/moonshine-software/moonshine/assets/11013417/d6623c25-422e-4097-9e42-5af3505d943f)

Так как переменная `$values` пустой массив, а не коллекция. Возможное решение:

`$values = $this->toValue() ?? [];`

заменить на

`$values = $this->toValue() ?? collect();`

в 384 строке.

**Comment by lee-to** [comment]
Да массив там не в тему
