### ISSUE TITLE
json field error :Array to string conversion

### ISSUE THREAD

**Issue by saidjons** [moonshine-software/moonshine#854]
### MoonShine Version

2x

### Laravel Version

10

### PHP Version

8.1

### Database Driver & Version

mysql 8.0

### Description

I have this field:
   Json::make('Options', 'options')->onlyValue()->
                ->hideOnIndex() ,
                
     whenever i try to save it ends in error. array to string conversion.
     
     this data is not being converted to json. is there any function manually encode, decode before storing , retrieving?
     "options": {
        "1": {
            "value": "a"
        },
        "2": {
            "value": "s"
        },
        "3": {
            "value": "c"
        }
    },

### Steps To Reproduce

I 've tried both 1x and 2x versions.

**Comment by lee-to** [comment]
you also need to add cast for the model, carefully look at the documentation
