### ISSUE TITLE
Не работает asyncSearch в поле типа BelongsToMany

### ISSUE THREAD

**Issue by crick-ru** [moonshine-software/moonshine#857]
### MoonShine Version

2.9

### Laravel Version

10.3.3

### PHP Version

8.2.16

### Database Driver & Version

MariaDB 10.11.6

### Description

На сайте funmatched.ru используется moonshine. В том числе есть форма ввода. Под капотом это обычный ресурс с раздельными page. Поле типа BelongsToMany с включенным asyncSearch и selectMode

Вот полный исходный код проблемного поля ввода:
`BelongsToMany::make('Победители', 'winners', function ($item) {
                return $item->name . " / " . $item->publisher->name_short;
            }, resource: new CharacterResource())
                ->selectMode()
                ->asyncSearch()
                ->customAttributes([
                    'data-max-item-count' => $num_winners,
                    'data-no-choices-text' => 'Начни вводить название колоды',
                    'data-no-Results-Text' => 'Персонаж не найден',
                    'data-item-Select-Text' => '',
                    'data-max-Item-Text' => 'Больше добавлять нельзя',
                ])
                ->withImage('logo', disk: 'characters')
                ->required(),`

Вот на этом видео один из клиентов пробует вводить что-то в это поле: https://vk.com/video-197566654_456239322
У него в Safary не получается в принципе хоть что-то вводить в поле. Не появляется клавиатура.
Также на видео видно, что он тоже самое пытается делать в браузере Chrome и Яндекс. Опять же со слов клиента Яндекс и Chrome он поставил только сегодня специально для теста. То есть можно предполагать, что версии этих браузеров самые свежие из доступных на платформе iOs.

### Steps To Reproduce

В мобильных браузерах Safary, Chome на платформе iOs при попытке войти в поле (тап на поле) не появляется клавиатура для ввода. В поле не получается ничего ввести.

На браузере Яндекс ввести получается, но не работает asyncSearch. Ни одно из вводимых значений, которые точно есть в базе, не находятся и не отображаются.

**Comment by crick-ru** [comment]
На всякий случай дополню. Баг воспроизводится только на мобильных браузерах на платформе iOs. На ПК и на android не воспроизводится.

**Comment by crick-ru** [comment]
https://vk.com/video-197566654_456239323

Еще одно видео от этого же пользователя. На нем явно видно, что при первой попытке активировать поле ничего не происходит. Но если зайти в другое поле типа "Text", а потом вернуться в Select (он же BelongsToMany), то и клавиатура появляется и asyncSearch начинает нормально работать.

Очень похоже на единичный баг на единичном устройстве iPhone. Но в предыдущем видео пользователь 3 браузера перебрал. Потому все еще есть предположение, что баг возможен и в moonshine.

**Comment by lee-to** [comment]
Да choices js в режиме тегов не работает на ios браузерах

**Comment by crick-ru** [comment]
> Да choices js в режиме тегов не работает на ios браузерах

Issue в choises написать? Они, вроде, не отечественные. На английском не вывезу.

**Comment by lee-to** [comment]
> > Да choices js в режиме тегов не работает на ios браузерах
> 
> Issue в choises написать? Они, вроде, не отечественные. На английском не вывезу.

нет смысла, они забили на свой проект, там 200+ issue и последний релиз в 2022 году
будем пытаться исправить сами или форкать их репу и править или же брать другую либу
