### ISSUE TITLE
Ошибка при добавлении Checkbox::make

### ISSUE THREAD

**Issue by ZmeyGAR** [moonshine-software/moonshine#87]
Call to protected method Leeto\MoonShine\Fields\Field::isGroup() from scope Illuminate\Filesystem\Filesystem

при создании блока в ресурсе админки и добавлении чекбокса вылетает крит ошибка
Block::make('form', [
                ID::make()->sortable(),
                Checkbox::make('Активный', 'active'),
            ]),

**Comment by lee-to** [comment]
Спасибо что нашли баг! Исправлено
