### ISSUE TITLE
Экспорт не учитывает queryTags

### ISSUE THREAD

**Issue by alglyzin** [moonshine-software/moonshine#887]
### MoonShine Version

2.11.2

### Laravel Version

11

### PHP Version

8.2

### Description

Возможно ли это поправить, либо я могу на это поведение повлиять сам ?

### Steps To Reproduce

Без особых условий

**Comment by alglyzin** [comment]
Проблема решилась неполностью. У кнопки экспорта query параметр с тегом не добавится на лету при нажатии на тег, а только после обновления страницы. То есть если нажать на тег и сразу на экспорт - выгрузится все равно все что есть.

**Comment by lee-to** [comment]
> Проблема решилась неполностью. У кнопки экспорта query параметр с тегом не добавится на лету при нажатии на тег, а только после обновления страницы. То есть если нажать на тег и сразу на экспорт - выгрузится все равно все что есть.

Добавится, сбросьте кеш, там фикс в js

**Comment by alglyzin** [comment]
Спасибо за оперативный фикс.
