### ISSUE TITLE
Экспорт огромных списков

### ISSUE THREAD

**Issue by alglyzin** [moonshine-software/moonshine#889]
### MoonShine Version

2.11.2

### Laravel Version

11

### PHP Version

8.2

### Description

src\Handlers\ExportHandler.php
В функции process экспорта нужно добавить что-то вроде того:

```php
        function itemsGenerator($data): Generator
        {
            foreach ($data as $item) {
                yield $item;
            }
        }

        $fastExcel = new FastExcel(itemsGenerator($data));
```

Иначе происходит переполнение памяти при экспорте больших данных. Проверял, код Выше работает.

### Steps To Reproduce

В моем случае экспорт > 200000 строк

**Comment by lee-to** [comment]
Вы можете создать класс и наследовать от ExportHandler и заменить его в ресурсе на свой изменив логику либо подготовьте pr

**Comment by lee-to** [comment]
В целом буду рад увидеть PR

**Comment by lee-to** [comment]
Хотя я все же добавлю сам правку на генераторах, спасибо за совет
