### ISSUE TITLE
Models with Composite primary key hydrate error

### ISSUE THREAD

**Issue by fed8055** [moonshine-software/moonshine#890]
### MoonShine Version

2.10

### Laravel Version

11.0

### PHP Version

8.2

### Database Driver & Version

postgres 14

### Description

i have this on the model
`protected $primaryKey = ['case_id', 'achievement_id'];`

created resource, etc...
got this error
other resources working well
![изображение](https://github.com/moonshine-software/moonshine/assets/65348350/ab6f5352-29cb-4926-bd85-3a13c74701a7)

### Steps To Reproduce

create model with composite primary key
create moonshine resource for this model and register it in the provider
open index page of this resource

**Comment by lee-to** [comment]
```php
/**
     * The primary key for the model.
     *
     * @var string
     */
    protected $primaryKey = 'id';
```

ключ должен быть строкой, если бы в ларавел была типизация то вы бы не смогли даже на уровне ларавел указать массив

**Comment by lee-to** [comment]
У вас даже на уровне ларавел половина методов работать не будет
к примеру Article::query()->find(1) выдаст ошибку что не ожидает массив и тд тп
Это не стандартный случай которые не имеет отношение к тому как сейчас из коробки работает ларавел, поэтому вам нужно использовать не готовый крад а делать свои страницы, на канале есть урок об этом

**Comment by fed8055** [comment]
> У вас даже на уровне ларавел половина методов работать не будет к примеру Article::query()->find(1) выдаст ошибку что не ожидает массив и тд тп Это не стандартный случай которые не имеет отношение к тому как сейчас из коробки работает ларавел, поэтому вам нужно использовать не готовый крад а делать свои страницы, на канале есть урок об этом

блин, вы правы. как-то я слишком поверил в легаси код.

**Comment by lee-to** [comment]
> > У вас даже на уровне ларавел половина методов работать не будет к примеру Article::query()->find(1) выдаст ошибку что не ожидает массив и тд тп Это не стандартный случай которые не имеет отношение к тому как сейчас из коробки работает ларавел, поэтому вам нужно использовать не готовый крад а делать свои страницы, на канале есть урок об этом
> 
> блин, вы правы. как-то я слишком поверил в легаси код.

Я видел есть пакеты которые фиксят эту проблему в ларавел, соответственно вам можно поставить что то из этих решений и реализовать в муншайн крад самостоятельно под эту модель

**Comment by fed8055** [comment]
если кто-то забредёт сюда с такой же проблемой, то я решил это через ларавелевский мутатор
```
protected array $compositePrimaryKey = ['case_id', 'achievement_id'];

protected function id(): Attribute
{
    return Attribute::make(
        get: fn() => implode('', $this->compositePrimaryKey)
    );
}

```
