### ISSUE TITLE
Json поле - перетаскивание блоков - orderable

### ISSUE THREAD

**Issue by Sckatik** [moonshine-software/moonshine#897]
### MoonShine Version

2.11.4

### Laravel Version

10.48.8

### PHP Version

8.2.2

### Database Driver & Version

Mysql 8.1.0

### Description

Использую поле Json в нем установлен asRelation. Сделана custom Page.
```
         Json::make('Блоки', 'mainPageLayouts')
                ->asRelation(new MainPageLayoutResource())
                ->fields([
                    ID::make()->sortable(),
                    Number::make('order', 'order')->required(),
                    Text::make('name_layout', 'name_layout')->required(),
                    Select::make('Тип блока', 'type')
                        ->options([
                            'slider' => 'Слайдер',
                            'text' => 'Текст'
                        ])->required(),
                ])->reorderable(true)
                ->creatable()
                ->removable()
                ->buttons([
                    ActionButton::make('')
                        ->method('updateOrCreateItem')
                        ->icon('heroicons.outline.pencil-square')
                        ->customAttributes(['class' => 'btn-primary'])
                        ->showInLine(),
                    ActionButton::make('', '#')
                        ->icon('heroicons.outline.trash')
                        ->onClick(fn() => 'remove()', 'prevent')
                        ->customAttributes(['class' => 'btn-secondary'])
                        ->showInLine(),
                ])
                ->default([])
```

В таком режиме недоступно перетаскивание и сортировка блоков внутри Json. Подскажите это так задумано? 
Или все таки возможно сделать? Сейчас добавил поле order -   Number::make('order', 'order')->required() и по нему буду менять блоки местами. Админу нужно вписать руками номер по порядку блока. Конечно, не очень удобно, хотелось бы перетаскивать их drag n dropom.

Заметил, что если не использовать asRelation - появляется возможность перетаскивания блоков.

https://disk.yandex.ru/i/2WCAijLSePZ3xA

### Steps To Reproduce

Добавить поле Json и в нём указать asRelation

**Comment by lee-to** [comment]
Специально фиксируем отключение реордера для asRelation так как это быстрое решение где нет ендпоинта реордера а сами отношения в процессе не удаляются а обновляются, поэтому в реордере нет смысла

Вы можете менять поле Number с сортировкой и делать order самого отношения, либо написать свое решение через TableBuilder и сделать ендпоинт реордера так как вы хотите

**Comment by lee-to** [comment]
Или оставьте просто поле Json но подобно тому как мы делаем замените changeFill чтобы наполнить поле из отношения и onAfterApply чтобы сохранить его с реордером
