### ISSUE TITLE
LayoutBuild

### ISSUE THREAD

**Issue by sashagm** [moonshine-software/moonshine#904]
### MoonShine Version

2.11.5

### Laravel Version

11.4.0

### PHP Version

8.3.6

### Database Driver & Version

MariaDB 10.4

### Description

Could not check compatibility between App\MoonShine\MoonShineLayout::build(): Contentne\Components\Layout\LayoutBuilder and MoonShine\Contracts\MoonShineLayoutContract::build(): MoonShine\Components\Layout\LayoutBuilder, because class Contentne\Components\Layout\LayoutBuilder is not available

### Steps To Reproduce

Чистая установка, 
# php artisan moonshine:publish

  Types:
  Assets ........................................................................................................ assets
  Assets template ...................................................................................... assets-template
  Layout ........................................................................................................ layout
  System Resources (MoonShineUserResource, MoonShineUserRoleResource) ........................................ resources
❯ layout

 Layout published

**Comment by sashagm** [comment]
Method 'App\MoonShine\MoonShineLayout::build()' is not compatible with method 'MoonShine\Contracts\MoonShineLayoutContract::build()'.intelephense(P1038)

**Comment by lee-to** [comment]
Пришли содержимое своего MoonShineLayout

**Comment by sashagm** [comment]
```
<?php

declare(strict_types=1);

namespace App\MoonShine;

use MoonShine\Components\Layout\{Content,
    Flash,
    Footer,
    Header,
    LayoutBlock,
    LayoutBuilder,
    Menu,
    Profile,
    Search,
    Sidebar};
use MoonShine\Components\When;
use MoonShine\Contracts\MoonShineLayoutContract;

final class MoonShineLayout implements MoonShineLayoutContract
{
    public static function build(): LayoutBuilder
    {
        return LayoutBuilder::make([
            Sidebar::make([
                Menu::make(),
                When::make(
                    static fn() => config('moonshine.auth.enable', true),
                    static fn() => [Profile::make(withBorder: true)]
                ),
            ]),
            LayoutBlock::make([
                Flash::make(),
                Header::make([
                    Search::make(),
                ]),
                Content::make(),
                Footer::make()
                    ->copyright(fn(): string => sprintf(
                        <<<'HTML'
                            &copy; 2021-%d Made with ❤️ by
                            <a href="https://cutcode.dev"
                                class="font-semibold text-primary hover:text-secondary"
                                target="_blank"
                            >
                                CutCode
                            </a>
                        HTML,
                        now()->year
                    ))
                    ->menu([
                        'https://moonshine-laravel.com/docs' => 'Documentation',
                    ]),
            ])->customAttributes(['class' => 'layout-page']),
        ]);
    }
}

```

**Comment by sashagm** [comment]
на use ругался но прошелся вручную проставил use MoonShine\   заработало вроде или я хз чтот сделал

**Comment by lee-to** [comment]
в чем issue то ? ошибок в коде нет

**Comment by sashagm** [comment]
> в чем issue то ? ошибок в коде нет   

use Contentne на чистой установке тут ошибка


`<?php

declare(strict_types=1);

namespace App\MoonShine;

use Contentne\Components\Layout\{Content,
    Flash,
    Footer,
    Header,
    LayoutBlock,
    LayoutBuilder,
    Menu,
    Profile,
    Search,
    Sidebar};
use MoonShine\Components\When;
use MoonShine\Contracts\MoonShineLayoutContract;

final class MoonShineLayout implements MoonShineLayoutContract
{
    public static function build(): LayoutBuilder
    {
        return LayoutBuilder::make([
            Sidebar::make([
                Menu::make(),
                When::make(
                    static fn() => config('moonshine.auth.enable', true),
                    static fn() => [Profile::make(withBorder: true)]
                ),
            ]),
            LayoutBlock::make([
                Flash::make(),
                Header::make([
                    Search::make(),
                ]),
                Content::make(),
                Footer::make()
                    ->copyright(fn(): string => sprintf(
                        <<<'HTML'
                            &copy; 2021-%d Made with ❤️ by
                            <a href="https://cutcode.dev"
                                class="font-semibold text-primary hover:text-secondary"
                                target="_blank"
                            >
                                CutCode
                            </a>
                        HTML,
                        now()->year
                    ))
                    ->menu([
                        'https://moonshine-laravel.com/docs' => 'Documentation',
                    ]),
            ])->customAttributes(['class' => 'layout-page']),
        ]);
    }
}
`
