### ISSUE TITLE
HasMany Вываливается из верстки

### ISSUE THREAD

**Issue by ACW-Digital** [moonshine-software/moonshine#907]
### MoonShine Version

2.11

### Laravel Version

10.10

### PHP Version

8.1

### Description

![image](https://github.com/moonshine-software/moonshine/assets/124562667/5b8db517-306f-46c9-94d5-0fefcbb1226a)
![image](https://github.com/moonshine-software/moonshine/assets/124562667/c3dda2a8-493b-4ef3-a54a-939c8fad299c)
Has many Field вываливается из верстки

### Steps To Reproduce

![image](https://github.com/moonshine-software/moonshine/assets/124562667/5b8db517-306f-46c9-94d5-0fefcbb1226a)
![image](https://github.com/moonshine-software/moonshine/assets/124562667/c3dda2a8-493b-4ef3-a54a-939c8fad299c)
Has many Field вываливается из верстки

**Comment by lee-to** [comment]
https://cutcode.dev/articles/kastomizaciia-stranicy-formy-moonshine-20
