### ISSUE TITLE
Съезжает верстка полей даты

### ISSUE THREAD

**Issue by Ard2p** [moonshine-software/moonshine#909]
### MoonShine Version

2.11.4

### Laravel Version

11

### PHP Version

8.3

### Description

При среднем экране едет верстка у полей даты
![image](https://github.com/moonshine-software/moonshine/assets/5220449/d05d5efc-73e9-425c-938e-09db5b460652)

### Steps To Reproduce

сделать 2 поля в декораторе флекс в небольшой колонке

**Comment by lee-to** [comment]
Вообще в узких местах флексы не используют и вам нужно самостоятельно контроллировать адаптивность и на определенных экранах делать блоки

**Comment by lee-to** [comment]
Совсем выключать мозг тоже не дело

**Comment by DissNik** [comment]
Решение данной проблемы:

```
Date::make('Created', 'created_at')
      ->withTime()
      ->customWrapperAttributes(['class' => 'overflow-hidden'])
```
