### ISSUE TITLE
QueryTag::make()->translatable()

### ISSUE THREAD

**Issue by kapuniko** [moonshine-software/moonshine#915]
### MoonShine Version

2.11.7

### Laravel Version

10.48.8

### PHP Version

8.1

### Description

В ресурсе:
 `QueryTag::make(`
`                'Archived_tasks', // Tag Title`
`                static fn(Builder $query) => $query->where('is_archived', true) // Query builder`
`            )->translatable('moonshine::task')`
            
В фалах перевода:
en: 'Archived_tasks' => 'Archive'
ru: 'Archived_tasks' => 'Архив'

в URL строке всегда хочется ожидать ?query-tag=**archived-tasks** (который указан сейчас в Tag Title),
но он, благодаря методу translatable() превращается либо в ?query-tag=**archive** либо в ?query-tag=**arxiv**, в зависимости от выбора языка. 

Добавьте, пожалуйста, в QueryTag второй параметр, как это сделано у Fields, где первым параметром мы передаём Title, а вторым - то что пойдёт в URL

### Steps To Reproduce

При выборе английского языка - URL 
![image](https://github.com/moonshine-software/moonshine/assets/99337224/18f91c09-22e2-425a-876d-0ff5c6a33dc6)

При выборе русского языка - URL 
![image](https://github.com/moonshine-software/moonshine/assets/99337224/4cb54081-f210-4b89-af04-986be4f6253d)

Хочется там видеть одну и туже переменную 🙏

**Comment by lee-to** [comment]
В пн сделаем

**Comment by lee-to** [comment]
```php
QueryTag::make(
    'Archived_tasks',
    static fn(Builder $query) => $query->where('is_archived', true)
)->translatable('moonshine::task')->alias('archived-tasks')
```

**Comment by kapuniko** [comment]
Спасибо большое! 🙏
