### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by tarun-pixeleyez** [moonshine-software/moonshine#923]
### MoonShine Version

1.52

### Laravel Version

11.0

### PHP Version

8.2

### Description

I am trying to install moonshine in my laravel project but got error.
![image](https://github.com/moonshine-software/moonshine/assets/159905617/7dbcce85-2f1b-4147-a125-89a05d3d0067)

### Steps To Reproduce

I have not tried any

**Comment by lee-to** [comment]
Make sure that your console version of composer/php meets your expectations and I also see that you are trying to install an old version of Moonshine (1.52). There are no problems with installing Moonshine now, what you indicate in the task is related to your environment
