### ISSUE TITLE
Limit items in HasMany

### ISSUE THREAD

**Issue by Annikangl** [moonshine-software/moonshine#931]
### MoonShine Version

2.12.3

### Laravel Version

10.48.10

### PHP Version

8.2

### Database Driver & Version

mysql 5.7

### Description

Не отрабатывает метод limit() при попытке ограничить количесто записей на странцие просмотра родителя.
![1](https://github.com/moonshine-software/moonshine/assets/32800337/ec04e415-63f1-45be-8d28-bfeb810df4b4)
![2](https://github.com/moonshine-software/moonshine/assets/32800337/f640592b-5aae-441c-9195-ac64d3bd4be4)

### Steps To Reproduce

```
  public function detailFields(): array
    {
        return array_merge($this->indexFields(), [
            HasOne::make('Промокод', 'promocode', resource: new PromocodeResource()),
            HasMany::make(
                'Созданные PDF',
                'commercialOffers',
                resource: new CommercialOfferResource()
            )->limit(5),
            HasMany::make(
                'Созданные подборки',
                'selections',
                resource: new SelectionResource()
            )->limit(1),
            HasMany::make(
                'Push уведомления',
                'pushNotifications',
                resource: new PushNotificationResource()
            )->limit(1),
        ]);
    }
```

**Comment by lee-to** [comment]
limit работает для вывода внутри таблицы когда скажем есть ArticleResource и он на главной странице выводит свои элементы где в таблице есть таблица HasMany

**Comment by lee-to** [comment]
То что вы показываете это вывод записей отношения и лимиты нужно ставить в методе отношения
