### ISSUE TITLE
При использовании поля JSON в качестве отношения в методы ...aplay() приходят не верные данные.

### ISSUE THREAD

**Issue by forest-lynx** [moonshine-software/moonshine#939]
### MoonShine Version

2.13.1

### Laravel Version

11.7.0

### PHP Version

8.2

### Description

Добрый день!
В форме ресурса использую поле Json как отношение. Пытаюсь трансформировать дынные у поля отношения через onBeforeAplay(), согласно документации должна приходить Модель, Значение и Поле. Фактически приходит родительская модель, вторым параметром "false" третьим Поле (как и должно быть). Логичнее было бы что, если Json используется как отношение, чтоб приходила модель отношения, а не родительская, ну и само значение поля вторым параметром. 

### Steps To Reproduce

Кроме того, для проверки взял пакет [moonshine-curency](https://github.com/yurizoom/moonshine-currency) метод resolveOnApply() не отработал в Json поле.

**Comment by lee-to** [comment]
В метод apply попадает текущая модель, значение из реквеста и текущее поле
Мы не несем ответственности за поля вне организации moonshine-software, пишите issue автору пакета

**Comment by forest-lynx** [comment]
Отсылка к пакету была условная. Не обращаем внимание на пакет. 
Имеем ресурс 1 с полем:
`Text::make('Name')->onBeforeApply(function(Model $item, $value, Field $field){...})`
Если происходит работа с непосредственно с ресурсом 1 то все нормально имеем модель ресурса 1 и значение из реквеста верное, и поле верное.
В ресурсе 2 используем поле Json:
`Json::make('','ресурс_1')->asRelation(new Ресурс_1())`
При этом в методе onBeforeAplay уже имеем модель ресурса 2, значение из реквеста приходит "false", поле верное.
Не логично для работы поля Json в режиме отношения получать родительскую модель. 
_Как тогда изменить значение поля перед сохранением в БД._

**Comment by lee-to** [comment]
> Отсылка к пакету была условная. Не обращаем внимание на пакет. 
> 
> Имеем ресурс 1 с полем:
> 
> `Text::make('Name')->onBeforeApply(function(Model $item, $value, Field $field){...})`
> 
> Если происходит работа с непосредственно с ресурсом 1 то все нормально имеем модель ресурса 1 и значение из реквеста верное, и поле верное.
> 
> В ресурсе 2 используем поле Json:
> 
> `Json::make('','ресурс_1')->asRelation(new Ресурс_1())`
> 
> При этом в методе onBeforeAplay уже имеем модель ресурса 2, значение из реквеста приходит "false", поле верное.
> 
> Не логично для работы поля Json в режиме отношения получать родительскую модель. 
> 
> _Как тогда изменить значение поля перед сохранением в БД._

Теперь понял, ок, возвращаю issue, спасибо
