### ISSUE TITLE
TableBulder throws TypeError when using Paginator

### ISSUE THREAD

**Issue by macocci7** [moonshine-software/moonshine#944]
### MoonShine Version

2.13.1

### Laravel Version

laravel/framework 11.7.0

### PHP Version

8.3.6

### Database Driver & Version

SQLite 3.37.2

### Description

Using Paginator as an argument to TableBuilder as written in the documentation will result in a TypeError.

[https://moonshine-laravel.com/docs/resource/advanced/advanced-table_builder#paginator](https://moonshine-laravel.com/docs/resource/advanced/advanced-table_builder#paginator)

### example1:

```php
        $paginator = User::paginate();
        return [
            TableBuilder::make()
            ->fields([Text::make('email')])
            ->items($paginator->items())
            ->paginator($paginator)
        ];
```
results in as follows

![moonshine_exception_01](https://github.com/moonshine-software/moonshine/assets/19181121/7963dceb-4c6b-4b92-991a-1051a4f2209f)

### example2:

```php
        return [
            TableBuilder::make(
                items: User::paginate()
            )
                ->fields([Text::make('email')])
        ];
```
results in the same as example1.

### example3:

```php
        $paginator = User::paginate();
        return [
            TableBuilder::make()
                ->fields([Text::make('email')])
                ->items($paginator->through(fn ($item) => $item->toArray()))
                ->paginator($paginator)
        ];
```
goes well.

**Comment by lee-to** [comment]
The TableBuilder works with arrays; if you don’t have arrays, you need to add castes
https://moonshine-laravel.com/docs/resource/advanced/advanced-table_builder#cast
->cast(ModelCast::make(User::class))

**Comment by macocci7** [comment]
> The TableBuilder works with arrays;

@lee-to Thank you for your commet. It should be documented, I think.

The documentation

[https://moonshine-laravel.com/docs/resource/advanced/advanced-table_builder#basics](https://moonshine-laravel.com/docs/resource/advanced/advanced-table_builder#basics)

says:

```php
TableBuilder::make(
    Fields|array $fields = [],
    array|Paginator|iterable $items = [],
    ?Paginator $paginator = null
)
```

**Comment by lee-to** [comment]
> > The TableBuilder works with arrays;
> 
> @lee-to Thank you for your commet. It should be documented, I think.
> 
> The documentation
> 
> https://moonshine-laravel.com/docs/resource/advanced/advanced-table_builder#basics
> 
> says:
> 
> ```
> TableBuilder::make(
>     Fields|array $fields = [],
>     array|Paginator|iterable $items = [],
>     ?Paginator $paginator = null
> )
> ```

Yes, we have problems with the documentation, we will be glad if you can help

**Comment by macocci7** [comment]
OK. I'll do as I can.

But I don't know the policy of documentation for this project.
Should I update the documentation based on the code implementation?

The constructor of `MoonShine\Components\TableBuilder` accepts `Paginator` at present:

```php
    public function __construct(
        Fields|array $fields = [],
        Paginator|iterable $items = [],
        ?Paginator $paginator = null
    ) {
```

**Comment by lee-to** [comment]
yes it can accept a paginator but each element iterable must be an array or use cast
