### ISSUE TITLE
Не понятно активно ли поле при переходе по Tab на поля Select, BelongsTo, BelongsToMany->selectMode()

### ISSUE THREAD

**Issue by forest-lynx** [moonshine-software/moonshine#945]
### MoonShine Version

2.13.1

### Laravel Version

11.7.0

### PHP Version

8.2

### Description

Добрый день!
Когда в форме осуществляется переход между полями по Tab не понятно получили ли поля Select, BelongsTo, BelongsToMany в режиме selectMode() фокус, список не раскрывается, лишь после нажатия любой клавиши происходит раскрытие списка. Кроме того, при активированном поиске у поля, если нажать стрелки в строке поиска отображается название нажатой кнопки и ввод других символов уже не доступен. При переходе на поле по таб с включенным поиском и началом ввода данных для поиска поле становится активным и список раскрывается.

### Steps To Reproduce

!

**Comment by lee-to** [comment]
У нас нет фронтенд разработчика в команде для данной задачи, пометил issue как help wanted, если найдется разработчик для данной задачи то будем рады

**Comment by lee-to** [comment]
problem with the Choices js library
