### ISSUE TITLE
Добавить функцию nullable к полю JSON

### ISSUE THREAD

**Issue by povly** [moonshine-software/moonshine#969]
### Description

Можно добавить функцию nullable к полю JSON, чтобы был пустым. А то нужно их оставить пустым в некоторых случаях. И когда сохраняешь, там устанавливается первый элемент с пустыми значениями. Было бы удобно просто пустым оставить и можно проверить количество массивов когда нужно на сайте показать)

**Comment by lee-to** [comment]
Теперь будет просто фильтровать пустые
