### ISSUE TITLE
Передача значения поля Date в другое поле с использованием reactive()

### ISSUE THREAD

**Issue by maxsus** [moonshine-software/moonshine#971]
### MoonShine Version

2.13

### Laravel Version

11.7

### PHP Version

8.3

### Database Driver & Version

SQLite

### Description

При выборе даты, значение не передается в связанное поле.

```php
Date::make('Дата', 'date')
    ->reactive(function (Fields $fields, $value, Field $field, array $values) {
        //$field->setValue($value);
        $fields->findByColumn('number')->setValue($value);
        return $fields;
    }),
Text::make('Номер', 'number')
    ->reactive(),
```
Выбранная дата в поле Text не отображается, в js консоли вылетает ошибка: 
```
app.js?v=2.13.1.0:9 DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('date') does not support selection.
    at Vr._afterCallback (http://127.0.0.1:8000/vendor/moonshine/assets/app.js?v=2.13.1.0:14:46501)
    at http://127.0.0.1:8000/vendor/moonshine/assets/app.js?v=2.13.1.0:9:37553
```
![2024-05-20_02-41-37](https://github.com/moonshine-software/moonshine/assets/102555738/d9c3b694-600e-4364-ae37-6836a7591a8d)
При этом, в ответе от сервера новые значения присутствуют:
```
values: {date: "2024-06-04", number: "2024-06-04"}
```
Само поле Date после выбора значения визуально меняется.

При отсутствии комментария на третей строке ошибка также присутствует.
При применении реактивности из поля Text ошибка также присутствует.
При изменении Date на Text ошибка пропадает, так что сама по себе реактивность используется правильно, думаю.

### Steps To Reproduce

1. Создать поля Date и Техt
2. Вызвать reactive() у поля Date или Text
3. Выбрать дату из выпадающего календаря или ввести вручную

Ожидаемый результат:
- Выбранная дата отобразиться в поле Date
- Выбранная дата отобразиться в поле Text
- Ошибок в консоли нет

Фактический результат:
- Выбранная дата отображается в поле Date
- Выбранная дата **не отображается** в поле Text
- В консоли появляется ошибка

**Comment by lee-to** [comment]
На всякий оставлю пример двойного изменения

```php
Date::make('Дата', 'date')
    ->reactive(function (Fields $fields, $value, Field $field) {
        $field->setValue($value);
        $fields->findByColumn('number')?->setValue($value);
        return $fields;
    }),

Text::make('Номер', 'number')
    ->reactive(function (Fields $fields, ?string $value) {
        if(preg_match('/\d+-\d+-\d+/', $value ?? '')) {
            $fields->findByColumn('date')
                ?->setValue(date('Y-m-d', strtotime($value)));
        }

        return $fields;
    }),
```
