### ISSUE TITLE
Проблема с отображением вкладок

### ISSUE THREAD

**Issue by dragomano** [moonshine-software/moonshine#984]
### MoonShine Version

2.14.1

### Laravel Version

11.8

### PHP Version

8.2.18

### Description

По статье https://cutcode.dev/articles/kastomizaciia-stranicy-formy-moonshine-20 поля были разделены по вкладкам. В 2.13.1 всё работало и отображалось. В 2.14.1 отображаются только заголовки вкладок, а в консоли ошибки:

`Uncaught ReferenceError: tabs is not defined`
`Uncaught ReferenceError: activeTab is not defined`

![sshot-26](https://github.com/moonshine-software/moonshine/assets/229402/dc0bd182-e336-4666-9839-3ab4c62c08a1)

### Steps To Reproduce

https://cutcode.dev/articles/kastomizaciia-stranicy-formy-moonshine-20

**Comment by DissNik** [comment]
Кэш сбрасывали? Изменился js, возможно он у вас закэширован, вьюхи тоже поменялись

**Comment by lee-to** [comment]
https://demo.moonshine-laravel.com/admin/page/profile-page в демке тоже 2.14.1 и вкладки в порядке

**Comment by dragomano** [comment]
И с кэшем и без, никак. В разных браузерах проверил.

**Comment by DissNik** [comment]
а ассеты точно новые?

**Comment by dragomano** [comment]
Дата у файлов в `public/assets` - 21.05, в консоли отображается загрузка файла vendor/moonshine/assets/app.js?v=2.14.1.0

**Comment by dragomano** [comment]
Пересоздал проект с нуля, пошагово, проблем нет. Значит действительно с обновлением это не связано, буду копать дальше.
