### ISSUE TITLE
При 2 колонках не везде применяется атрибут

### ISSUE THREAD

**Issue by Ard2p** [moonshine-software/moonshine#995]
### Description

При 2 колонках не везде применяется атрибут и странно что он применился на последнюю где находятся экшен кнопки

![image](https://github.com/moonshine-software/moonshine/assets/5220449/d7aa5611-dc31-4635-8250-c953d5a0b1bf)
![image](https://github.com/moonshine-software/moonshine/assets/5220449/1ca394e4-e202-4881-8e22-92fe2d4e4b0f)
![image](https://github.com/moonshine-software/moonshine/assets/5220449/60701af5-0679-4cfc-92e7-eff983dc5178)
![image](https://github.com/moonshine-software/moonshine/assets/5220449/c460f373-009a-47b5-8805-29b915502604)

**Comment by Ard2p** [comment]
Теперь не получается прописать в TableBuilder свои tdAttributes, из за этого перенес ActionButton из buttons в listFields
![image](https://github.com/moonshine-software/moonshine/assets/5220449/d8202de0-d002-4468-b393-6ddfedf6f215)
 
 и проблема повторилась
 
 
![image](https://github.com/moonshine-software/moonshine/assets/5220449/3861ca18-6745-48f3-bb70-c102856566ba)

но теперь я ожидаю что у обоих столбцов будет padding: 0

**Comment by lee-to** [comment]
Да сейчас только один элемент Td допускается с tdAttributes, когда несколько то стройте через TableBuilder -> tdAttrubutes либо через Resource tdAttributes
Остальные изменения будут уже в 3 версии
